const articles = [
  // gpu
  {
    name: "ASUS ROG Strix AMD Radeon RX 6700 XT OC 12GB GDDR6",
    images: [
      "https://by3301files.storage.live.com/y4mQFLnYlVONV6bfNNBR9tKfZhin78h363ZLoC2F9GgU5d7n6WoRdyyKWHbhUdeOibq_KmLOzdg9I9-qsTlOvkz9RvdqJNrTQV__NYv9MC1HbXQK5u3dDIjc0fxSDYIjjIukaHFSqU8dE3Mr9hrkwh-LhZB9u4sTY3f1LJWZ0x4tgKehT_B9L5AkAKPDnjJiH09?width=679&height=744&cropmode=none",
      "https://by3301files.storage.live.com/y4m0qr5XDTgVl0CKFhrMHIg2HM-Umz5ojKUnwLf447xavywcb5ROj_FvOEWzfrjgq3kFT-baFdvkWqHMNaMLQU7UbsPK4wZ-ktQuCLY80BJjIgDBcKUQMW0gweNMYjff3nAHZC0JsZYC5d7nY4Oj_V-VXg4_LKvs6xj3jqXY-ulVYhxJmXAAWEQvQbWxHwMQ4Gu?width=602&height=450&cropmode=none",
      "https://by3301files.storage.live.com/y4mFzylNnUbcnoBkhvb32NiJPHZd9pKWFtf1TOJaiWq7kWBJS9YYNUTw-uY8-U4QdACJfeDTWu48gcwtwIMxCKXdbSsACF-vzc1DefDb8hDl82d3iU3CbTbI83FloTywjHUqSSuAHbQnYXWtA49TK7TczcuRbtrDW897A9NvTSx4baZhmRFM-Mkwu59EpEX7ceD?width=524&height=450&cropmode=none",
    ],
    price: 1330.0,
    stock: 5,
    brand: "ASUS",
    category: "GPU",
    description: [
      "Axial-tech Fan Design has been enhanced with more fan blades and a new rotation scheme",
      "2.9-slot design expands cooling surface area compared to last gen for more thermal headroom than ever before",
      "Super Alloy Power II includes premium alloy chokes, solid polymer capacitors, and an array of high-current power stages",
      "MaxContact heat spreader allows 2X more contact with the GPU chip for improved thermal transfer",
      "Reinforced frame prevents excessive torsion and lateral bending of the PCB",
      "FanConnect II equips a hybrid-controlled fan header for optimal system cooling",
      "Vented backplate prevents hot air from recirculating through the cooling array",
    ],
    imagesDescription: [],
  },
  {
    name: "ZOTAC GAMING GeForce GTX 1650 OC 4GB GDDR6",
    images: [
      "https://by3301files.storage.live.com/y4mnW5UautNfibQDbA8PybHWJeBa44FFN46EX5uSycwBzHeBhqtKAn77kReiNogr90GG9rT9my1ju3FEJwKOTTNyxMYQgSrRIfCWFIXkb0Y_PeQGWw6KayIlNsf-RfUx7IUXVFtsCb0CfVL_T24BcgHGFPvS4wCHIIadZNmLNWzCSxKd2UH_86SyygxQr8f3Hit?width=1500&height=1061&cropmode=none",
      "https://by3301files.storage.live.com/y4mkDfpXMb_T89-FZDZ0gXPT5B8zasxZp5LQ3xL3MGQstkFPBVxKyExwuMINnYy6GP-p9KPs9OcgfzVwDqsM3kg1-cqLYl9kU7IdJd_pYitu5WwRSz8a_GvFQ8XgLc0bbV9u5SdL0ByrCuxUM7Ub9muzMpTglPA5jWiS9Uh5LavirIN3TShuspyioOtC_YQkUcG?width=1500&height=867&cropmode=none",
      "https://by3301files.storage.live.com/y4mPL-121MYGyTmaXKqIPcu54nOU9d5x27oIvkM2OdbubDji8rF3xW1o_t6oo8pYmveTpdUc8nT7mMOlfhS6ScvzDCWZHgxweodlOqPFsdPZwoKV2hLAw7elNjo6gxBzz3p1kebPu4hsIiSyjVnzd3hZK4Gb6Law4txsoQDG1c6wy9pqvCTzJ326enXfF_Ss6q0?width=1500&height=1074&cropmode=none",
      "https://by3301files.storage.live.com/y4muoSvCzaQvPMrd3gHzSCecgNdwxhAKFp5fdNPZe3hmc46W547mVmSZSF8oVEGejzXg76uhqR-IQHQJpMQpgaa_21zhOd7CUM4MZnw05oDQLCmltDK4c4Z2j6ODsddq2k6SB8asijtPG2SpZfBsDqgu5zsMT0qHmGyge5qdJhe-6dlafpYqcuuemkoHvrzqPYJ?width=1500&height=1149&cropmode=none",
    ],
    price: 324.99,
    stock: 5,
    brand: "ZOTAC",
    category: "GPU",
    description: [
      "New Turing Architectur",
      "4GB 128-bit GDDR6",
      "Super Compact 5.94-inch Card, Fits 99% of Systems",
      "Dual slot, 4K Ready, PCI Bus Powered",
      "DisplayPort 1.4, HDMI 2.0b, DL-DVI-D",
      "Boost Clock 1620 MHz",
    ],
    imagesDescription: [],
  },
  {
    name: "ASUS GeForce RTX 2060 OC 6GB GDDR6",
    images: [
        "https://by3301files.storage.live.com/y4mYif-k0DYOFmAE4avvqNBy-76lhdrO1iu42nq9um6lVPA1SnyhXGQJWzRCP_O9duvwdiSk4Um0z3kDDWvGuuqcwgK4H9jbKmDKuAdld9_5RUxGzjpeUNXCo_NhmOQRVwoVW5e5wgbMPKsnQrN00tsc78jK7RmuDsdPW-vcaPDvqs9NHR4pFQVzwg0K0m7ZBDY?width=1500&height=1475&cropmode=none",
        "https://by3301files.storage.live.com/y4me7stmrUIc3xtIK5R3nzcBJrw8eC1hkq-rcmS9yot4f89e_IaKY_YDZ5eAPJCPZ7zSVenmtYxJydEi3B6xkDSkW-ChxTMWAiq6adnmo29TkMmR8YXsGQFC9_V6AL1rTcnLb16zAD62U-m0-8CpPS1Cfil0GrbX-EFx7f3u5WwxXGHmRrYMzong0Ju2GlaIyWb?width=1500&height=1393&cropmode=none",
        "https://by3301files.storage.live.com/y4mAsHnWThSrupnOeG_R47PeX2zoeY5hkO75ZpMSsq0csoQpF_iU2evk6X-ON3dKgPxWzWDff_2fceSPguOxN30CHAvOIqkF9aICeBDGIzAH6u1yI1hLuBU8WXw3zEcBObYnnFRVlYbu-ZzxZ3BumYtw6IULc3BhdZJMY9seTvosA1yGcWVATYR_ZHd7myQcddV?width=1500&height=1429&cropmode=none",
    ],
    price: 696.00,
    stock: 5,
    brand: "ASUS",
    category: "GPU",
    description: [
        "Powered by NVIDIA Turing with 1785 MHz Boost Clock, 1920 CUDA cores and overclocked 6GB GDDR6 memory",
        "Supports up-to 4 monitors with DisplayPort 1. 4, HDMI 2. 0 and DVI ports",
        "Wing-Blade Fans boasts IP5X dust-resistance and operates at 0 dB levels when temperatures hit below 55C.",
        "Protective Backplate features a durable aluminum construction to prevent PCB flex and trace damage.",
        "GPU Tweak II makes monitoring performance and streaming in real time easier than ever, and includes additional software like Game Booster, XSplit Gamecaster, WTFast and QuantumCloud",
    ],
    imagesDescription: [],
  },
  {
    name: "",
    images: [],
    price: 0,
    stock: 5,
    brand: "",
    category: "GPU",
    description: [
        "",
        "",
        "",
        "",
        "",
    ],
    imagesDescription: [],
  },
  {
    name: "",
    images: [],
    price: 0,
    stock: 5,
    brand: "",
    category: "GPU",
    description: [
        "",
        "",
        "",
        "",
        "",
    ],
    imagesDescription: [],
  },
];
