const articles = [
  // GPU

  {
    "name": "ASUS ROG Strix AMD Radeon RX 6700 XT OC 12GB GDDR6",
    "images": [
      "https://by3301files.storage.live.com/y4mQFLnYlVONV6bfNNBR9tKfZhin78h363ZLoC2F9GgU5d7n6WoRdyyKWHbhUdeOibq_KmLOzdg9I9-qsTlOvkz9RvdqJNrTQV__NYv9MC1HbXQK5u3dDIjc0fxSDYIjjIukaHFSqU8dE3Mr9hrkwh-LhZB9u4sTY3f1LJWZ0x4tgKehT_B9L5AkAKPDnjJiH09?width=679&height=744&cropmode=none",
      "https://by3301files.storage.live.com/y4m0qr5XDTgVl0CKFhrMHIg2HM-Umz5ojKUnwLf447xavywcb5ROj_FvOEWzfrjgq3kFT-baFdvkWqHMNaMLQU7UbsPK4wZ-ktQuCLY80BJjIgDBcKUQMW0gweNMYjff3nAHZC0JsZYC5d7nY4Oj_V-VXg4_LKvs6xj3jqXY-ulVYhxJmXAAWEQvQbWxHwMQ4Gu?width=602&height=450&cropmode=none",
      "https://by3301files.storage.live.com/y4mFzylNnUbcnoBkhvb32NiJPHZd9pKWFtf1TOJaiWq7kWBJS9YYNUTw-uY8-U4QdACJfeDTWu48gcwtwIMxCKXdbSsACF-vzc1DefDb8hDl82d3iU3CbTbI83FloTywjHUqSSuAHbQnYXWtA49TK7TczcuRbtrDW897A9NvTSx4baZhmRFM-Mkwu59EpEX7ceD?width=524&height=450&cropmode=none",
    ],
    "price": 1330.0,
    "stock": 5,
    "brand": "ASUS",
    "category": "GPU",
    "description": [
      "Axial-tech Fan Design has been enhanced with more fan blades and a new rotation scheme",
      "2.9-slot design expands cooling surface area compared to last gen for more thermal headroom than ever before",
      "Super Alloy Power II includes premium alloy chokes, solid polymer capacitors, and an array of high-current power stages",
      "MaxContact heat spreader allows 2X more contact with the GPU chip for improved thermal transfer",
      "Reinforced frame prevents excessive torsion and lateral bending of the PCB",
      "FanConnect II equips a hybrid-controlled fan header for optimal system cooling",
      "Vented backplate prevents hot air from recirculating through the cooling array",
    ],
    "imagesDescription": [],
  },
  {
    "name": "ZOTAC GAMING GeForce GTX 1650 OC 4GB GDDR6",
    "images": [
      "https://by3301files.storage.live.com/y4mnW5UautNfibQDbA8PybHWJeBa44FFN46EX5uSycwBzHeBhqtKAn77kReiNogr90GG9rT9my1ju3FEJwKOTTNyxMYQgSrRIfCWFIXkb0Y_PeQGWw6KayIlNsf-RfUx7IUXVFtsCb0CfVL_T24BcgHGFPvS4wCHIIadZNmLNWzCSxKd2UH_86SyygxQr8f3Hit?width=1500&height=1061&cropmode=none",
      "https://by3301files.storage.live.com/y4mkDfpXMb_T89-FZDZ0gXPT5B8zasxZp5LQ3xL3MGQstkFPBVxKyExwuMINnYy6GP-p9KPs9OcgfzVwDqsM3kg1-cqLYl9kU7IdJd_pYitu5WwRSz8a_GvFQ8XgLc0bbV9u5SdL0ByrCuxUM7Ub9muzMpTglPA5jWiS9Uh5LavirIN3TShuspyioOtC_YQkUcG?width=1500&height=867&cropmode=none",
      "https://by3301files.storage.live.com/y4mPL-121MYGyTmaXKqIPcu54nOU9d5x27oIvkM2OdbubDji8rF3xW1o_t6oo8pYmveTpdUc8nT7mMOlfhS6ScvzDCWZHgxweodlOqPFsdPZwoKV2hLAw7elNjo6gxBzz3p1kebPu4hsIiSyjVnzd3hZK4Gb6Law4txsoQDG1c6wy9pqvCTzJ326enXfF_Ss6q0?width=1500&height=1074&cropmode=none",
      "https://by3301files.storage.live.com/y4muoSvCzaQvPMrd3gHzSCecgNdwxhAKFp5fdNPZe3hmc46W547mVmSZSF8oVEGejzXg76uhqR-IQHQJpMQpgaa_21zhOd7CUM4MZnw05oDQLCmltDK4c4Z2j6ODsddq2k6SB8asijtPG2SpZfBsDqgu5zsMT0qHmGyge5qdJhe-6dlafpYqcuuemkoHvrzqPYJ?width=1500&height=1149&cropmode=none",
    ],
    "price": 324.99,
    "stock": 5,
    "brand": "ZOTAC",
    "category": "GPU",
    "description": [
      "New Turing Architectur",
      "4GB 128-bit GDDR6",
      "Super Compact 5.94-inch Card, Fits 99% of Systems",
      "Dual slot, 4K Ready, PCI Bus Powered",
      "DisplayPort 1.4, HDMI 2.0b, DL-DVI-D",
      "Boost Clock 1620 MHz",
    ],
    "imagesDescription": [],
  },
  {
    "name": "ASUS GeForce RTX 2060 OC 6GB GDDR6",
    "images": [
      "https://by3301files.storage.live.com/y4mYif-k0DYOFmAE4avvqNBy-76lhdrO1iu42nq9um6lVPA1SnyhXGQJWzRCP_O9duvwdiSk4Um0z3kDDWvGuuqcwgK4H9jbKmDKuAdld9_5RUxGzjpeUNXCo_NhmOQRVwoVW5e5wgbMPKsnQrN00tsc78jK7RmuDsdPW-vcaPDvqs9NHR4pFQVzwg0K0m7ZBDY?width=1500&height=1475&cropmode=none",
      "https://by3301files.storage.live.com/y4me7stmrUIc3xtIK5R3nzcBJrw8eC1hkq-rcmS9yot4f89e_IaKY_YDZ5eAPJCPZ7zSVenmtYxJydEi3B6xkDSkW-ChxTMWAiq6adnmo29TkMmR8YXsGQFC9_V6AL1rTcnLb16zAD62U-m0-8CpPS1Cfil0GrbX-EFx7f3u5WwxXGHmRrYMzong0Ju2GlaIyWb?width=1500&height=1393&cropmode=none",
      "https://by3301files.storage.live.com/y4mAsHnWThSrupnOeG_R47PeX2zoeY5hkO75ZpMSsq0csoQpF_iU2evk6X-ON3dKgPxWzWDff_2fceSPguOxN30CHAvOIqkF9aICeBDGIzAH6u1yI1hLuBU8WXw3zEcBObYnnFRVlYbu-ZzxZ3BumYtw6IULc3BhdZJMY9seTvosA1yGcWVATYR_ZHd7myQcddV?width=1500&height=1429&cropmode=none",
    ],
    "price": 696.0,
    "stock": 5,
    "brand": "ASUS",
    "category": "GPU",
    "description": [
      "Powered by NVIDIA Turing with 1785 MHz Boost Clock, 1920 CUDA cores and overclocked 6GB GDDR6 memory",
      "Supports up-to 4 monitors with DisplayPort 1. 4, HDMI 2. 0 and DVI ports",
      "Wing-Blade Fans boasts IP5X dust-resistance and operates at 0 dB levels when temperatures hit below 55C.",
      "Protective Backplate features a durable aluminum construction to prevent PCB flex and trace damage.",
      "GPU Tweak II makes monitoring performance and streaming in real time easier than ever, and includes additional software like Game Booster, XSplit Gamecaster, WTFast and QuantumCloud",
    ],
    "imagesDescription": [],
  },
  {
    "name": "ASRock Phantom Gaming D Radeon RX 570 ",
    "images": [
      "https://by3301files.storage.live.com/y4m-cq3FqAl5H32JhHhEu3P3gYhyRmMPCnntxEo3gofCNEj05S6RDuaB_l6oplqsWFNB13E5M7rI3Zlfjyvc5VhK-RX-5E-HhVTaPoINXv3Ph2ywWaha8Xw9OZ_--YJBHIQFWDi88Vp-cY28GBDWkhXpA_cUM_r92vCPHjhRh3bFd0Qp6vYINB2nAF3y2kdDTIJ?width=1131&height=800&cropmode=none",
      "https://by3301files.storage.live.com/y4mEayW9_upWZeVOu5NYz1moFluhoEOBYc6hrn2ayKbAmfQ87Yz-p8YuLC_U0un4xpi1_mXGxo-eLflaMss6jZYjuUTAbLWQ76FbqjZvqfuHtG32YjmSrL-mJlK8JDEv355jEYBMMgTH5XZFBO68JQJiDABY-Wcw5s_Qfn603Ycl7Vqb5h5uTkGzMqXgpUSc7KI?width=1124&height=588&cropmode=none",
      "https://by3301files.storage.live.com/y4mCV7EJUl7p8xgQvWp4rYbReKrzeg19TiOQEVRJr3xlgv_fEQ02ATcRDwhVbEql8RjpzKGUM8aIxGAYpTPxDVJhnOoGj5L_WGwRI7w2UMP_MM83CtviJriocDhEBSmnVuFCEWwTpXzosUET6taH-gxdIQ4x3Yx9Jt17Jp9LyTqJNkAbH75bOXygYGm7RBtDNXY?width=1200&height=932&cropmode=none",
      "https://by3301files.storage.live.com/y4m0Vu1LpD85fgwygtDrcbBJJSq42KY2H41s0JwsjWNbCChB-DAVk2-vAjHYqPJIKYTuC8ux7PbI3ApSRX8HqOlIXUzQw3eIb5IomUP_fM2xG0e0tS7FU5DuqPRsb9SFYCwvx3BeMb35jOo0YcGwh-gDNe7GfI86ZQ3wIursx5reXREzAmE0Nc7ypp45n4yCFkS?width=1200&height=420&cropmode=none",
    ],
    "price": 498.86,
    "stock": 5,
    "brand": "ASRock",
    "category": "GPU",
    "description": [
      "4GB 256-Bit GDDR5, Default Mode: 1244 MHz",
      "Core Clock OC Mode: 1293 MHz",
      "1 x Dual-link DVI-D 1 x HDMI 2.0 3 x DisplayPort 1.4",
      "PCI Express 3.0 x16",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Sapphire Technology Pulse AMD Radeon RX 6600 XT",
    "images": [
      "https://by3301files.storage.live.com/y4mW4sQ9QYMXm6aE9bL085Y3aighq6LYf453fC8OW8GOV2GV8u2YyCTOGZnwn6gGOHW6Wphn7v8y0zNMfk39jmnjEdYuF3uRmr7Jo3OrRM91o3x1Au6av8d41SS2n-n2psx0HUyhe5xpIyDyMMIv348D5JZtp4Ul5HgJn4zt_lZdhsikI7JMB54WwQFIllimz60?width=1500&height=1386&cropmode=none",
      "https://by3301files.storage.live.com/y4mfcxQ_jq3Od90fVHx6OWh5uUrZdlrR6OT5D1SA2mVqXORiAc3E791Zmo-dRYubdKMOEuPhBzCYZMJOnZ9N0yKAFyZkdCzlDcofa2nleqCiE0oKgCWRa1_cA3kwWK3Eb8V2y0V22mhcqTYv37DA7joUVy_Nw7s-MQ6OgM9lk2wIwvYb3s5W_mjU0CGdh5pPsfg?width=1500&height=797&cropmode=none",
      "https://by3301files.storage.live.com/y4mJ3M-CvI1jmksvxkLEzgb1IAm8yC3-b6q8p8Vlngjcny759Ds1DPxUQYbQTHKVxLUjUEJSZemj4VszTc6wDuGeDAd1gIBnaDN7yPg-YUlsKSFlErkjzyjb64x3OjsEmnCsf-ecbMUxpUaa3Lgn4sxLITsnS3MNX8Ixj1cfIu_3IMXuxMaA0Qq9VlMu853cVJa?width=1500&height=1041&cropmode=none",
      "https://by3301files.storage.live.com/y4mfcxQ_jq3Od90fVHx6OWh5uUrZdlrR6OT5D1SA2mVqXORiAc3E791Zmo-dRYubdKMOEuPhBzCYZMJOnZ9N0yKAFyZkdCzlDcofa2nleqCiE0oKgCWRa1_cA3kwWK3Eb8V2y0V22mhcqTYv37DA7joUVy_Nw7s-MQ6OgM9lk2wIwvYb3s5W_mjU0CGdh5pPsfg?width=1500&height=797&cropmode=none",
    ],
    "price": 659.0,
    "stock": 17,
    "brand": "Sapphire",
    "category": "GPU",
    "description": [
      "Memory Size: 8192 MB",
      "Memory Interface: 128-bit DDR6",
      "External Power: 1 x 8 pin",
      "Video Streaming up to 8K",
      "PCI-Express 4.0",
    ],
    "imagesDescription": [],
  },
  {
    "name": "",
    "images": [],
    "price": 0,
    "stock": 5,
    "brand": "",
    "category": "GPU",
    "description": ["", "", "", "", ""],
    "imagesDescription": [],
  },

  // RAM

  {
    "name": "Crucial RAM 8GB DDR4 2666 MHz CL19",
    "images": [
      "https://by3301files.storage.live.com/y4m7HSqDdMFDPwu414BnWsnggWlwK23oXrNukD9mW3LCUt6BVjA8pscWdW0hv9cS5pfeYFk8bdK09kBbxIhPlRxofNxJ5hbXOpUl1YP5y1Llnh6nEzF_XBlIPo5O4xdFkta3F5F5cTeM8cQuhinj9jkJsVJ-zkF31_quE1T5eFsq4DDp1Se5zarntgJ42ZX2S6O?width=1500&height=800&cropmode=none",
      "https://by3301files.storage.live.com/y4mU1jOaBhlQxQ2UYebOgswLU6sAwWOJ0_69BF12rhn848lI6m3oq5KfVRSWqdHvI-07daVTQi8l92kcxbvPhtvUWhlNpv8BRagxKtA1qqmnBBnqw-xqbsaWu2_COEvFyHEqR5Q2gH8vWlNMpdDzZ8XoZYZxoahI9zGHQ9OSD2hgLUH7iYoKgRCh1-KCU20O3SP?width=1024&height=238&cropmode=none",
      "https://by3301files.storage.live.com/y4mGryFa_csvip_hT2RvZzrSmhzIqA-KDhCIxyCpv2xvvSd3KN-Mf2sIEG2x3Y9aXfbwroZKzP0blnvIckMv9HSBznKHByMgw66-uLYU3vTCdoFqONsoPqSmIlkR6CajWKWuwud8bEEHQWANYuYKQIfuYBrpDsn_uZ70d-dYx_QVnw7qWmkkeedCEQ-NWQzMvsv?width=1280&height=853&cropmode=none",
    ],
    "price": 34.99,
    "stock": 18,
    "brand": "Crucial",
    "category": "RAM",
    "description": [
      "Improve your system's responsiveness, run apps faster and multitask with ease",
      "Install with ease; no computer skills required How-to guides available at Crucial",
      "Compatibility assurance when using the Crucial System Scanner or Crucial Advisor Tool",
      "Micron quality and reliability is backed by superior component and module level testing and 42 years of memory expertise",
      "ECC Type = Non-ECC, Form Factor = UDIMM, Pin Count = 288-pin, PC Speed = PC4-21300, Voltage = 1.2V, Rank and Configuration = 1Rx16, 1Rx8 or 2Rx8",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Crucial Ballistix 3200 MHz DDR4 DRAM Desktop Gaming Memory Kit 32GB",
    "images": [
      "https://by3301files.storage.live.com/y4mJpCv0uDnVDAeTnBoxTo5TrMsFNXidB9Qva6AoLfSp5aYQ0nXVYlf-1_g9C24z4O8Yx33KlZhf9qBMnBYk9tqeTBI2m5j88OJbvzc0OuTaRorxi4ULM5QJDZKZQ2wX5ESr60NQamjeqlGJmGrpVT9vw1j0CQA-q76k1YaKFSK1JgdG3U_6FsQiWwihcwWitNT?width=1024&height=299&cropmode=none",
      "https://by3301files.storage.live.com/y4mkDR84vLFGV9pCYzsTXplVKd1gMde2XTSp_Hlt7ntNWx0M2AovQVlDUG3SLKi7tYSOOi7IXXhLuTW8CQkaYzcugEkJctR2QUquA5rYUvaB3KP8L_ekzlyKp9Do1gCW6OMeHZzAmsN086fOAMQ1Q4-2rYVsiyc1cf0qQs1f86DTXQmdT5NryXYKgDH-qJpIYO3?width=1124&height=348&cropmode=none",
      "https://by3301files.storage.live.com/y4mf5SiQv8TqC_yqrr1Ox3-GJJZZzkammo04Ca_OsarYuzuza5a0K0WR8fKhuDahM4PsLFNirLVj-CLb6HvheUHvYDjJsoTBhKKWg-ybvuAWdwNzTQv3-eopHbZGewRlMhBC5UZ7nfH0LUr5b4jRX5faxNtAyanDndX3cYLIBJwoO0FU76iWCEU-r8MjkIy2uIQ?width=1280&height=1280&cropmode=none",
    ],
    "price": 89.99,
    "stock": 15,
    "brand": "Crucial",
    "category": "RAM",
    "description": [
      "Ideal for gamers and performance enthusiasts",
      "Engineered for the latest AMD and Intel platforms",
      "XMP 2.0 support for automatic overclocking or run at JEDEC default profile",
      "Modern aluminum heat spreader available in multiple colors to match your system build or style",
      "Voltage - 1.35V",
    ],
    "imagesDescription": [],
  },
  {
    "name": "HyperX Fury 16GB 2666MHz DDR4",
    "images": [
      "https://by3301files.storage.live.com/y4mZKZ7Y9DZEiabWy2M8HhJ1MV3aM86PAzd4-ggCKhqzytj3omlWr0KbzmK5C_jKRynWSnHX-40Lq6L94YQ5d4Wf1O9ky_nlOyyN7H8uBQCizsYkLlt4Sn54KdPMAceELv9OIwOfn98JZFjSHiDn_72ymIEW4My0fAoZ32pbHKBUgpnSFAf5VylPpTvZck9Iock?width=1250&height=685&cropmode=none",
      "https://by3301files.storage.live.com/y4mB49DIrBWG-nBCxpVCv5SBw9NRh-2bFCY2BThjbQwg1h759hRLToVd8IlPVWFoElGtDwMJ9IELVZOQ7IWpMJmlsmYjWKq-zJI60p89gXYggoicOBcB-fwU_3vJn-W0E7CNUaQxVqngw-v8EFGcrpEu4e9H926IOkVBohq0VPZP1Ix2C39vgjzID2AszeqTEir?width=1280&height=332&cropmode=none",
      "https://by3301files.storage.live.com/y4m-G9lnn4WBSa479bkLlgaveielQ_EBaSM38khKHcaNR43NSt5vWZXaYzKK88snT6eO3Lu_zFTvOoIdvYI8DHEj8N301AUrIeNKadiDVEEGs5VB8eK6TW1PJK9D80mOar_AvtmKE_EV2NDZcvGladGq-p3PjRJdNLNCWqH8UlpShxBokG2iYNu6ez6daDtQjOE?width=1276&height=332&cropmode=none",
    ],
    "price": 99.5,
    "stock": 19,
    "brand": "HyperX",
    "category": "RAM",
    "description": [
      "Updated low-profile heat spreader design",
      "Cost-efficient, high-performance DDR4 upgrade",
      "Intel XMP-ready profiles optimized for Intel’s latest chipsets",
      "Available in fast speeds up to 3466MHz",
      "Plug N Play functionality at 2400MHz and 2666MHz",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Astra-Gear 8GB(1x8GB) 2666MHz DDR4",
    "images": [
      "https://by3301files.storage.live.com/y4mx1ueGot2cKGNFMXps_JR3IE444B3PYFBYXGchE-C0V80NmqdbUAcVPA4vFZOyM9bJnyYpnbVfGS0z_BOxGnWvyrYNLMnKAGlzpHZ2rWsC47GJwyxNfvEZdMnbjDcwRuN9HFLOjX1Rc2pgIT_U239iG_3hyqDYlLctGv7IFYW7F3eyTIUh85VZy5yGVMZq0CR?width=1500&height=661&cropmode=none",
      "https://by3301files.storage.live.com/y4mYhL5_R3P1NcJ-xu-mM0bNdeBhNEQms0AOX8iZUU5yviT2M4tttB-h8jIkdaMzrNIkhL2EqEOFn7OASpf0ztWCHBrz-EkNYVQ0QbFQqYhqkYvycSoUIYpBZEeTjOAPfUf8sGmm_tozHJmGTx7CNB1jItoNLrG_YbUFMmSKwIuzqc9bvc7QpfcCi_Qb85SYNIN?width=1500&height=374&cropmode=none",
    ],
    "price": 27.88,
    "stock": 17,
    "brand": "ASTRA GEAR",
    "category": "RAM",
    "description": [
      "Product Spec: 8GB(1 x 8GB Modules) | Type: DDR4 U-DIMM(288-Pin)| Memory Ram for Desktop",
      "Speed: DDR4 2666MHz | ECC Type: Non-ECC Unbuffered | Hynix IC",
      "Simple to install & Plug and Boost, NO technical skills required to upgrade your system performance with low working voltage at 1.2V",
      "To ensure the best reliability and compatibility, every memory kit is built with Strictly audited DRAM chips with top quality 10-layers of PCBs and tested on all major performance motherboard brands.",
      "Limited Lifetime Warranty. Please verify the supported memory(RAM) spec of your system before purchasing to ensure compatibility.",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Patriot Viper Steel DDR4 8GB 3000MHz",
    "images": [
      "https://by3301files.storage.live.com/y4mcscJZV-hdn48yye-MdKvbyKxS8S6Nu7Xlb9_Ij0fOdR6BuWSzi-QaksbYpg9LKlJhsIIXHMyEH9pk1AQ5UmY8BOegLJRjUucKbBs16Gv8XgKvTieZDU56diNcv1Qbw5G-G7NdWRGUWbVyEwHDR-1ATsUH46cVUFRnhyJRopdmSPVFE5XM8A9vYjPIk_egQFe?width=1500&height=502&cropmode=none",
      "https://by3301files.storage.live.com/y4mZvDW2hFZFqAqIGS_x_V3yUNSZW1aXl3rcVMT2KJNwKN9xNflyA5FcLOBdl1PfXszoML7mYmVkp0NkR8_poYIYmExEY3Zj6DUUl6X3xtzgGxjraNpenAiCE6I-ni2IPoSlYRTIN4_eg5Az5gfTQfJjgJ1XfpmA8boxG6ZV5ZA9P0lUt4SGTYkiM-BnLrVUxvC?width=1500&height=500&cropmode=none",
    ],
    "price": 35.0,
    "stock": 20,
    "brand": "Patriot Memory",
    "category": "GPU",
    "description": [
      "Capacity: DDR4 8GB Single Module",
      "Base Frequency: PC4-17000 (2133MHz); Tested Frequency Profile 1: PC4-24000 (3000MHz)",
      "",
      "",
      "",
    ],
    "imagesDescription": [],
  },

  // Cases

  {
    "name": "JONSBO MechWarrior MOD-3 Gaming Computer Cases",
    "images": [
      "https://by3301files.storage.live.com/y4m7lCNxSYZDFV2QyvEFVdl2JzZhijPAg9c2HJsmWOP0QjsSjTdr2EubsPMtop5rFjj21EggB9bFkEec-P4uj9C0EYrQQ7bVU8K5mZ1IIO4jyM9UP-H7d0a5Z3UyIQS0oPXOWVgeOHco3nHhME5Fqb9CzNrV5mXmeF0E142Kc6JNFy7MZgGnAY9ENlEucrvxcB9?width=730&height=892&cropmode=none",
      "https://by3301files.storage.live.com/y4maYDAg-BNu3VHNFF-E1D7949__-ov-B_tdIBfk-h9VZaxzZsuJuS1N68Ro-QlGW3AZXQkRqmTZq06VkRoZ7LOth6AKCdgF1gDCWq0OZmkJDbjkXuJMAnnXQSgUe4PWdHkpEfr7E_7kMSSGRE35bmB9vvQAqFQRCHBi6Ev6ivDa2kaiT2vh8K-dzgbhkBt4yPH?width=1256&height=1212&cropmode=none",
      "https://by3301files.storage.live.com/y4mMEOVnrOkeoIK18dD_uO0oeWe0oxQYuysRVv-HcCpXrvAHl7e2hponRcan4Ng9X6BBaCK1jk4VAH6yaWyKBkN0pfM0IXZPGSn4S6F5Vpv0dLR11xih8l-cfDlLsSjt8kww94znOAdBFY1ScuuuYrtYux0f25dVCvnPYreTXIiA0Ffl7SOyy8oKLJzB3ke4tGk?width=1500&height=1386&cropmode=none",
    ],
    "price": 499.99,
    "stock": 4,
    "brand": "HELLOLAND",
    "category": "CASE",
    "description": [
      "MechWarrior - Video Game Case",
      "Compatible with 142mm radiator; compatible with XL-ATX motherboards",
      "Front panel lighting supports 5V ARGB",
      "2323 '' span for cable management",
      "2.0 + 0.098 in Magnalium Solid Body",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Corsair 4000D - Gabinete ATX semitorre para PC",
    "images": [
      "https://by3301files.storage.live.com/y4mkJi-Qvp7TZYbj-0fmWtpzsxrao7bC8Ay-vB2m88EqWc1g_scRiqrPU6VkzC-yh6OWGecl0HUh32yFBf2Nr8ZVHv5Cx7EJEtbPiqy-VHQQCIkV9_RS2RlCnzxY-JZvOrdKAHQ5m2sipJh9rjrkisN6Gsn_j1FOm4S086U68E4KXoIXBWJbzCS1W66BHvqXDfF?width=989&height=1500&cropmode=none",
      "https://by3301files.storage.live.com/y4m10ks9UQ_O0VanHZx48Hdw6uQK6AIAjWuC27BMkiyTJeu25KucGwjQa8CRKCqIch7hTHMd202yzcCwjsujgTmObYJTNtYX8DQrpdZL7CxO4zJlx9NtCkjtahsxaOFcQgvHWe5C1OfGUJ7rHlINXzjZSsa0LLyryhNZQg3iazY455kvxFQqqhwsJdMoRtUC8Ar?width=1362&height=1500&cropmode=none",
      "https://by3301files.storage.live.com/y4mX8eZNLLTM7vIoTKkhqTq4pBt3HqacyEZY4EF6iN5RGeJwMCeoJYJnSY6dW71cBRpWz-O5VNXRHH8ial1eI9xkrfaW1or2zzmV7OabPkHx1UEoZHkNQsdXI9x3GakSZCiqWb_5D9ybLn2XKPi91KLGwQPoCdGSMwx1aEwhNJTLppwtdpOEeaQ5kd7Psrow6OS?width=1500&height=1500&cropmode=none",
    ],
    "price": 74.99,
    "stock": 5,
    "brand": "CORSAIR",
    "category": "CASE",
    "description": [
      "The CORSAIR RapidRoute cable management system makes it quick and easy to route main cables through a single channel, with a wide 0.98-inch (25mm) space behind the motherboard for all your cables.",
      "Includes two 4.72-inch (120mm) Corsair AirGuide fans, with anti-swirl blades to concentrate airflow and improve cooling.",
      "The spacious interior can accommodate a maximum of 6 4.72-inch (120mm) or 4 5.51-inch (140mm) fans, as well as multiple radiators, such as a 14.1-inch (360mm) on the front and an 11-inch (280 mm) at the top (based on RAM height)",
      "Put modern connections at your fingertips with a front I / O panel that includes a USB 3.1 Type-C port, USB 3.0 port, and a microphone and audio jack.",
      "Combining innovative cable management, concentrated airflow, and proven CORSAIR build quality, the 4000D is a fit choice for an immaculate high-performance computer.",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Cooler Master MasterBox MCB-B600L-KANN-S00 ATX Mid-Tower",
    "images": [
      "https://by3301files.storage.live.com/y4mJ0FRmFLmU-ywLBgow97InMwJBvLotFoCO7Ox7WSogeTmXIcH3KKf7MNWQXnggOoKpLEinGUCrgtKVo_yYnGNp_ZdUTUjtHRH9cUI07huDVi4Q662_-ZHFeXJP49myy_G6eAaskhHG2q9VnbWzMqjGukN_WdcoR9SWjsjQtqySOdXtoMSpHKObzaBHqjSm_RK?width=1328&height=1500&cropmode=none",
      "https://by3301files.storage.live.com/y4mvkFfqV2FADC-_y32QLYMNqIso5JtV98GWNwH5_jCYvuvIlcldRP0tLRkovWl_vPajoqOnelJ_Jojl2A-pPnbt-Um_19VPZDhRg_RIiLlEa9tdssPlNJqLWAgk7FGjfwD2LFDGNly4p0l-IAngkVJPH-x83BK9ChCBGsyJnAUUsHADq-VO0eCH-8K1HJUTr5x?width=1500&height=1474&cropmode=none",
      "https://by3301files.storage.live.com/y4mrh5ycag6yL5SYjzF_XVkXVJcUQdyaQUc4eEnwscaC1wNQJ2Z0k490nxfW0O9_svpQgpWrR7MqF3sSsnXDfrmhE69EhWWMXNwLfrltmc5FAY76cf4yatTRUVaXOBM70kEX1Z-ar1bpu1MVd6rIdqDxowB68ch9PvuLj9x_OxWwm0r80R6JeSegkw26JNQL72P?width=1193&height=1500&cropmode=none",
      "https://by3301files.storage.live.com/y4mrmBdF_0Q1NyEPauTsHLOgndC0-F7dmRb8ALsLjnODOKZzf9-a8K7-z57zivRSuzzhPy4oAJShgYSsBEJiKlt5StTDZGaMPym41hcRKS_efWXcDWa_7yAQnMQ4uMNV48-yWoylydNF0oikECMxjFMwujqa1OVEpXEDx2PNs344P5JEHVJLqImKdA2OAp4M-nG?width=1146&height=1500&cropmode=none",
    ],
    "price": 68.99,
    "stock": 5,
    "brand": "Cooler Master",
    "category": "CASE",
    "description": [
      "Elegant design with red side trim and acrylic side panel",
      "Supports 5mm x 47mm fans, 1 x pre-installed on the back",
      "Supports radiators up to 14,173 in.",
      "Supports GPU / VGA cards up to 400 millimeters",
      "Full black coating and PSU cover",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Apevia - Carcasa de computadora tono Crusader, Aura y Trinity",
    "images": [
      "https://by3301files.storage.live.com/y4mekrUNox1OAABq2C1xdhuWTXbsOsuzL_34SI8I7UXL2ZB_gMHjpG707NO4tkULwWjUEGVNhb9mBcVdnCrJ7_01se3Ps0Std6_iokPzYIR8WtGhtOCxu6CRrixqODgzgN2Y5IfoD_ATzh_fTroz620_pghcPmHpcfAqnUrdqsCzRoxBnoBk0RjCV3ZihYDoDso?width=403&height=500&cropmode=none",
      "https://bn1305files.storage.live.com/y4mb914wV0Qitpxxw-lWbAQhTzHhjE_I5W3NBZVPKOf845UStDnjdEp_jNOLtVbxjeMVRAHKtTWXENa-DsE5G9CEq48Ww9v7suYHOn9hShXAg-1wFqo687LKLCAPkBqdMyxhDr3SglIzU1w6lfz5eF0zWnZzVcELJxp9ZrrWzD8kPBNCphLifIhh0fz1uwh3bqi?width=684&height=843&cropmode=none",
      "https://by3301files.storage.live.com/y4mVNegHjGGLIrms76kcsy1MVkestiPUaVYXojZUbMe9giZuO8LVnYP585XZ6C7WoWVkcVWkA3peW3XHa5DE8tvSWxfnKjDxCi0xfwj8GV5gjkUvsGO-k7_bt6Xb7eJNH8-B5GK0DidxvCvvwYoKnYd856A6dAYTxxJBJc0lml4l7svolgrvD5WJXryUEdCeV_J?width=800&height=1220&cropmode=none",
    ],
    "price": 76.99,
    "stock": 5,
    "brand": "Apevia",
    "category": "CASE",
    "description": [
      "Contemporary solid steel ATX mid tower computer case, white, with 2 tempered glass windows (left / front) and 4 pre-installed RGB fans.",
      "Compatible with ATX / Micro ATX / ITX motherboard, USB 3.0 / USB 2.0 / HD audio ports and improved cable management.",
      "Supports VGA up to 55mm in length, CPU Cooler up to 64mm in height.",
      "Special click switches for the power button, reset button and RGB light switch button.",
      "Plays through 16 lighting modes via the front panel I / O RGB light switch. 30 total rendering options include: RGB, breath, single color, light off. The fans are patented on this case.",
    ],
    "imagesDescription": [],
  },
  {
    "name": "AeroCool Bolt-G-BK - Torre central de cristal templado RGB",
    "images": [
      "https://bn1305files.storage.live.com/y4mFxXQQpdqaY9cGd5ipcRcF7XshFNg5RHl9cP-LsMHRIWtaIbfHKAnRdctEub5NHuY9578H1DRE_dIfzxQPQrlxA-JdR-2gkHHZZ8AqUu4dtrsTudUDsEWQ4Clnu1oi6Cp7w-zbl0dnRXjMgVOZP5urVpoacRgxqrtL0L3_EXBC4c0xiuxi26nM7wDQRv3Np0t?width=403&height=500&cropmode=none",
      "https://bn1305files.storage.live.com/y4mvQ_AONRY9EuDgbihKfkanc3gWNfYDBMjeiqw3G33o4oFNiGJO7uHr6SYf2hxl3JwGju3qyAeMvIlWd3rh_rGfJ56tQWL7YdxXm5YY5UCOpM8CP8jDzho9CyEuM6G8Le2l00IKbu4DFIQDVs7WL4QeJPB9n2RNuPeW6rYj15V7xPIieihiVaj3ef4uup_aqFL?width=396&height=500&cropmode=none",
      "https://bn1305files.storage.live.com/y4m7rNPRbHmehz-0l5PX98upJ-E5Ys_y1NWFG5zjyjlIy9qyxMRazJnOx3DmcDyGw6qaHXc9PQH-6jwbmex17wbF4_H-8llH7f15inBnHsIj7jVJGfkio88JrwBLK9FkThMiW5nErNTdqzwL6oZ2K6tn7vT4bm1J1jOTx6mbQva2gmsUrSBgi4Ufpob-_lxNT_y?width=320&height=500&cropmode=none",
    ],
    "price": 49.99,
    "stock": 4,
    "brand": "AeroCool",
    "category": "CASE",
    "description": [
      "Sleek RGB LED design on the front panel",
      "Access to 13 preset lighting modes via conveniently located LED control button",
      "Full tempered glass side panel to show the inside of your rig",
      "Carbon fiber-style front panel offers a futuristic look and feel",
      "Dual chamber design for better ventilation",
    ],
    "imagesDescription": [],
  },
  {
    "name": "KEDIERS - 7 PCS RGB Fans ATX Mid-Tower PC Gaming Case Open",
    "images": [
      "https://bn1305files.storage.live.com/y4mS5iZI2RYnidfkPwhg7vU9USPR0OUHol1Mm7toI81PDY93A9kJHFPae39z2RFCCYt-bcOYGVX5ZFTQuMWDJTSnzkaFaFd1g2TW0Lw29VN3b_goMmDbowKMi6MYA0M1L6HMZb4g15GDryidH3KJOUj8U15cVBGFIQXguhYWsoSP61Peit9KDCjV8iX6jF6ABo5?width=1211&height=1500&cropmode=none",
      "https://bn1305files.storage.live.com/y4miHEuZQAUSMTAAckIWDVgCbSjDqvcx-Zyij859tRW4shRG-lIy02VO9z0oF4mzMuXZrMmwJPSq2WrK3TfJ8yKfPe490SdWGskyQcVz2VHObhBr4PuZA61cL_TNTIwBoGq-qxldeRqwSiH05m0GtOFEN1RFE50WjIBOKqxbMxJD9oLD0gdQTZzv5LJKx-6cNU1?width=1500&height=1500&cropmode=none",
      "https://bn1305files.storage.live.com/y4mw9F2eR1cch208gV721ktE4d92-0vIGwXSWJ4sK9vdcZEAFQ2Yw4JwS_CDaxmx46CirZ6_40P6rlXU2zbWMSuA4rlWUpg8L8VdpCYX1TUYsQK-isatoV19rPeW_aDdKfppFPDcJ9wb0SBzP4-6nryHIyxZMqHEVvjLiUoAsaJWbyzierdSUzFAyNLD-dAkcaL?width=1500&height=1500&cropmode=none",
    ],
    "price": 159.99,
    "stock": 6,
    "brand": "KEDIERS",
    "category": "CASE",
    "description": [
      "Powerful Cooling System: KEDIERS open computer case is pre-installed with 7 dual light ring LED fans: 3 front, 2 top, 2 side; The open design can keep the GPU continuously low, making your computer run more smoothly.",
      "[2 Panel Tempered Glass]: KEDIERS 570 gaming case is equipped with 2mm x 5mm thick translucent tempered glass, which can clearly see RGB lighting, which can protect and display all components in the building and bring better to the players.",
      "Synchronizable RGB Lighting via Motherboard - Allows you to control fan lighting with addressable 5V-3pin RGB motherboards. Compatible with motherboard software including US aura Sync, MSI Mystic Light Sync, etc.g",
      "[Panel I / O]: 1 USB 3.0 port, 1 USB 2.0 port, 1 HD audio, RGB button, Power button.",
      "[Remarkable expansion]: Support Mini ITX, M-ATX, ATX motherboard.",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Montech Fighter 500 Black ATX Mid-Tower Computer Gaming Case",
    "images": [
      "https://bn1305files.storage.live.com/y4m3kDNL2JrUkCCA9NLC-LG1srnC-sWMAKyHASRdK8mJHDv3NIomM6LPgpfAA1mctOx9doYYex8grdRYv--9iiFOiXKdpmDIVNaUHzJH7blGCvgxPtrxsIssEOrZrRaTI96T49HUZbknezUFMYaFQqhgsOYilA_4vsrq-IyyDZVPEE5Ng3wB3uep8-Db27Knnxq?width=974&height=1349&cropmode=none",
      "https://bn1305files.storage.live.com/y4mJE1tPTJBFwvyxa1F7yN8AJnbymH6kYPOkMlpXWSjB2MZNOEtnW4t_rpc-lkY41n9fho_vDFmIk3TRgg3ES8Yw2wABXYjyAeINGtheVz0JFzE_9rkA7ILJ3SHlRfnI81UyDi25_x6AVzoUn658M7Cg-E9ye8huz8usI0P3Es22Zt_2OK-Mc-Qw4ykijFRHsai?width=1237&height=1418&cropmode=none",
      "https://bn1305files.storage.live.com/y4mJYFggjwpID3tzyT9O_QJfMpeN4drbHU3P8SHAJQviJHbmmWjM7ufCIw76LyF0upcCmOw-KVDZflWTr9YqL4SK2MHZQUCw0pC5pOykXB9lnaB5yrnhrOTtxo_20ycNFODFlPx7HtMDY2gi6KyTQgIhEIx2ZGK4K0rNatFEGu1wvbYQBy4h4JWJlShrFEC2AZG?width=1229&height=1417&cropmode=none",
      "https://bn1305files.storage.live.com/y4mKQgzrYx_YRm32Nn_F0uiBTFx6UUPbwK1cZRJNt_EgEEFLz2c-_F9eSVf_GIjKeULvyTiq2HZQplV3PQibeoQvbs6vdEeOKf-leqXsoPQJNmdzCIq1s4PZpxfatlxz6h7ARosiYUWNH614fRqPiWojcQpBBs73hrMhGacVz_oPU71VhTEHuA1YKh2GpJ-lzrI?width=1452&height=1430&cropmode=none",
    ],
    "price": 66.99,
    "stock": 5,
    "brand": "Montech",
    "category": "CASE",
    "description": [
      "Full View Glass Side Panel - The large sized Glass Side Panel, allows for a full view of your PC setup and glorious chromatic lighting effects.",
      "Fine Metal Mesh Front - Large area front mesh with LED Rainbow fans allow maximum airflow and with the bottom mesh providing cooling for your power supply keeping everything stable.",
      "Unique Design with M Modeling Architecture - Front panel is not only designed with our logo of Montech, but also combined the top triangle with bottom triangle. This design makes this panel be unique.",
      "Dazzling Rainbow Fans - Four pre-installed dazzling LED Rainbow fans, for a glorious color space and lighting effects. Pre-installed 4 dazzling rainbow fans create gorgeous color space.",
      "Excellent Dust Resistance - Magnetic top vent screen provides excellent dust resistance and is easy to unmount.",
    ],
    "imagesDescription": [],
  },

  // Procesadores

  {
    "name": "Intel Core i3-9100 Desktop Processor 4 Cores up to 4.2 GHz LGA1151 300 Series 65W",
    "images": [
      "https://by3301files.storage.live.com/y4mGC0QttfFXrGGwCPYXood5yliv0-6vQe8pjB1jC8KTnA06uz56Rb-c9hBneHH5vBTnIyDUUs1wOhKq3Q4jg8CWlU8h1Ljfh6PJbE8MA15VlACR9n1m-JLbF54fT2psYVRD9LSyfsPBSL07OissDWvTZs73gE2hRkKAsurZhiCUAvANucIWW-SHUTtVbENb08p?width=1172&height=1348&cropmode=none",
      "https://by3301files.storage.live.com/y4mWPD-gjTBUK5MShWUgxfk4mwyo0lbpcrN2qtXbIzw7ENYZtGHdQcjHuyjEveRBdmmOF6f5vsn3SeZaITKizabLXzOKGhX362eaRokmYaWVs9PR_LQ7xRu659b_C8PX2aJHi2nRv5iNgSNjRwGY4i8zKaMJA5_BO3UUPRjJl57eww1vGgzs9Bc1x6wpLOU7Yzc?width=1148&height=1476&cropmode=none",
      "https://by3301files.storage.live.com/y4mn2SjWIWx1KjWsG2PckJcSlvTjW8WwDuyjOwWhh8JWXTFm2QD2UFq-3hDJhYlrJSbW8812vToKMH7M9GJsxKF71A1qJ5lm6hgWT9thgCofv5erggK2TJ5kcHaFIclrLbm3KoFNunX6acDmhMJkiK63eKW7ZyzYB8yu_82zGf0sPrrojBTg5tNp6gs9MN8iE8p?width=1170&height=1476&cropmode=none",
      "https://by3301files.storage.live.com/y4m6FoqpxSGxZfBl0tlmiiVFGpEC4JdAKj30T6AA5p9yCuV6MUS9w69HcUGroZo9FPMn6oG4RyX3NyaMWpxqGXIXVG9NSUVrKxcDNCDDtFnGKa8XQVD5_qVueVQgEzzjpONNWRVB84-bAlaIxMJoYIvZDLYvWxovQR7T6WM_HH2onL1aWwkl_QRALBu49QLdQPk?width=1080&height=1080&cropmode=none",
    ],
    "price": 153.7,
    "stock": 21,
    "brand": "Intel",
    "category": "Processor's",
    "description": [
      "4 Cores /4 Threads",
      "Up to 4.2 GHz",
      "Compatible with Intel 300 Series chipset based motherboards",
      "Bios update may be required for motherboard compatibility",
      "Supports Intel Optane Memory",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Intel Core i5-10400 Desktop Processor 6 Cores up to 4.3 GHz  LGA1200",
    "images": [
      "https://by3301files.storage.live.com/y4mYjWf8GxX3tm0CWYkqU1VpsQgugf5dDUg_D1Lhh_svrl9aMTCUzBsEpW2KYv0waqTCNdoyAYAPogOD9Jha-DZ23krgrGesJMY5IbmrbcdG9hruhZWwSstSnI0E6UUtbXNHGsLb8vL45h9PWWRP7o9aScNoZtsXiS7A4NjC4BBoKxWc7WEwRL6zteOdv-BC6HK?width=1500&height=1432&cropmode=none",
      "https://by3301files.storage.live.com/y4mwcjSR_jdPsvhVbTMxIC_DbkAVUz6P568SIX5WbhgLv8vPShaURmCYHdQd-85LMo9Rp1VLNuwIe2qTJrpBzIM6QLcW7Nr6AnJFxYZAzKJUiGIBOI82z-BZ04PponJdxW-43C3RnOIvODTn2aj8WqFpEbDqQ84MI4ZA4i60ICQOQc1otXyt24YEGn0RMmGMgbt?width=1500&height=1248&cropmode=none",
      "https://by3301files.storage.live.com/y4mYU9DQ8CY9m6FTEPpTf_ufWRkN_HDi3nawcZ_gO2CBzfhNeL5OB6CH3v-ekayeq5ZvmBraYFqEFfNyldPXoYyQjcqEKL5IVfsfUaT1XWedbZ0h5QewmWdm13lNekHRNS2dbf1uf3OuYy0DFEw93lCBWYQZGb9-gUTvHSho93kVQrMz7s1lHfv8fqueFLLhgiv?width=724&height=724&cropmode=none",
    ],
    "price": 156.93,
    "stock": 5,
    "brand": "Intel",
    "category": "Processor's",
    "description": [
      "6 Cores / 12 Threads",
      "Socket type LGA 1200",
      "Up to 4. 3 GHz",
      "Compatible with Intel 400 series chipset based motherboards",
      "Intel Optane Memory support",
      "Cooler included",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Intel Core i7-10700K Desktop Processor 8 Cores up to 5.1 GHz Unlocked LGA1200",
    "images": [
      "https://by3301files.storage.live.com/y4mffU6RBrFwMqwepczZABLbM19U0fbeAO6OLEtQtc_yNvjIidKraRt7sYzxgy3ZN2gD0gOa_dqdLzvgLE4jmyYsAN9Iwpme3NUoGWm2qafGgPzzRk7ZPW9-MvUUUvAT9PtM0vhuDDryW0P8kB9M7SSTYtYHf3lWjriXgzrrnwDPg5ES-aOWd6CL2CzkMhfKhxR?width=1310&height=1500&cropmode=none",
      "https://by3301files.storage.live.com/y4ms2TAKLf0cOzZ_FZsx4RcXmRslsae4SOyUfTzPB5vZ7FqXh63cdc_1J0UqjEeez8vfYsmOrjjkHY7tXi9iNVIPfLzZues4luHxHSkfOk9FIkCNAFbiIfy3aqwEgUEQfPzcqD1QR7fHxU3pNdkKDRsAB2M04e3AVxMlm11mtVUJp3nxs9IOXQksFUTCzURcaY6?width=1175&height=1500&cropmode=none",
      "https://by3301files.storage.live.com/y4m5CkbX0xH3VksF8B5rF8h4nccvuHzXwUW6Zdvkg4iARS5wpyvPcF6oBkCau2FXV1DOTgD-KJnAUzbdIQoloSTu7fnCnOtE8YMD55gh6tpKZEqxeeb4yjEfGIPSwwX-ch7Be4_ek8b-Q4Hq-IlOeSwqLsFCM7GAbFvnn5nZEHwUv6QooR85T0liJ7cVH1sN8cF?width=1255&height=1500&cropmode=none",
    ],
    "price": 339.96,
    "stock": 24,
    "brand": "Intel",
    "category": "Processor's",
    "description": [
      "8 Cores / 16 Threads",
      "Socket type LGA 1200",
      "Up to 5.1 GHz unlocked",
      "Compatible with Intel 400 series chipset based motherboards.Bus Speed: 8 GT/s",
      "Intel Turbo Boost Max Technology 3.0 support",
      "Intel Optane Memory support",
      "Graphics Base Frequency: 350 MHz",
    ],
    "imagesDescription": [],
  },
  {
    "name": "AMD Ryzen 3 3100",
    "images": [
      "https://by3301files.storage.live.com/y4mPkt4srWcGS2YVqIejzsFW_plneCkOtM5zq7DUYHlLEmmpwrCsfOTsKeKYjzouwI8Z16DqvDgqYMKKK68QB8tIOP5dYDWUDhKtMv9AaJOUactk78O1dvUkUtcgbSx-qkpfYNZHOttpvRflUu5f__UcANDsiU1SrXOYXvTCH9PLAzW-uWochSrD9y6RHBO0J9T?width=867&height=934&cropmode=none",
      "https://by3301files.storage.live.com/y4mFPiqBpykDr8o-40PTBCNdnh9VxxuVS6XTD6tpIWthWnJyNfLId1n5UnwBQkXEy1PEyhMVlgkC1KIrSIWWA8xLDjY0lq7GeedY875iJHlgZLwAI3Z5zhYhQO996sj2wTywn9Qm8XSPV6D2z7KSQ596lc_blCOeshUSp8HQccFL84nmwPwb-Pj--Ijc7KqqKYU?width=869&height=944&cropmode=none",
      "https://by3301files.storage.live.com/y4m6Kf5C7ykMgdYnKy9lt3QB1bkVg5umO0iz_hXXFotDRgaPH6BKGR-hmeyBa2OBGhgCXYn7NStk6D-1YDs0DzgXx_DleldNSql8SfUAQeLc0JnCcmAd-46CCY8gejDw9WoXwfRWeHqAfN-bYgPw5g9phmZJ5NJbt1k5pRI8sASULu_8xdfMzTZB5GvCPOVlmy4?width=444&height=308&cropmode=none",
    ],
    "price": 205.12,
    "stock": 5,
    "brand": "AMD",
    "category": "Processor's",
    "description": [
      "3rd Gen AMD Ryzen processors are the world's most advanced in the desktop PC gaming segment",
      "Can deliver smooth 100+ FPS performance in the world's most popular games, discrete graphics card required",
      "4 cores and 8 processing threads, bundled with the quiet AMD Wraith Stealth cooler",
      "3.9 GHz Max Boost, unlocked for overclocking, 18 MB of GameCache, DDR-3200 support",
      "For the advanced Socket AM4 platform, can support PCIe 4.0 on X570 and B550 motherboards",
    ],
    "imagesDescription": [],
  },
  {
    "name": "AMD Ryzen 5 5600X 6-core",
    "images": [
      "https://by3301files.storage.live.com/y4m29Gpp4cA1jzTAsZePJGLZsLWHewkVSKVop6bX4htn5_4WJ8Wp798F9xvHYqDoxneoiE_XCnkY2Zx7-pi2o95Hrzm8j0oaGi9X2iFHnVbs6URSJwlGkYbnRBh8yO5XojE8qyw5T8Gov2aqfP_MC837s6rdcPp6IWhezm7aOBn1fdo_fx5sw9AvR6GCTDo4Ffk?width=862&height=938&cropmode=none",
      "https://by3301files.storage.live.com/y4mI5ajRlK102TQmSpnUOM9QrkhuWjeRHR40LlzdtwXNIWoCk4xiRMvQubzoncu_BRYvaZiPrjGd3VnFCY4g1dHaMnMtcf0mVOfWDQlQ5fqMvLNNTBR4QeoGSZAMcjJDCUHHVzu9BarECP0bg8OfW-vGhBsRv55pCJD9M3sqerunSSnrr19PlV_oM4eWYaQ1LbX?width=421&height=422&cropmode=none",
      "https://by3301files.storage.live.com/y4mgV1XZEDfVA6YkkopcOvXzqMi0fl-sSD8IJUitk_SDKPeQDfZNWoe0hi5MI9CVror8D4Y_R53JKDbcO9tqAKiortgZ61w2guZwbRFdY0awY58JUSGWm_k_fjwqwuyT8nsTyNK8hCFvpJDLPYOlVk7M3jEhurKHT9pMt_qQb00FYlSXRlxFOcUVWnA_1yErhqL?width=1480&height=1498&cropmode=none",
    ],
    "price": 289.0,
    "stock": 5,
    "brand": "AMD",
    "category": "Processor's",
    "description": [
      "AMD's fastest 6 core processor for mainstream desktop, with 12 processing threads",
      "Can deliver elite 100+ FPS performance in the world's most popular games",
      "Bundled with the quiet, capable AMD Wraith Stealth cooler. System Memory Type: DDR4",
      "4.6 GHz Max Boost, unlocked for overclocking, 35 MB of cache, DDR-3200 support",
      "For the advanced Socket AM4 platform, can support PCIe 4.0 on X570 and B550 motherboards",
    ],
    "imagesDescription": [],
  },
  {
    "name": "AMD Ryzen 7 5700G 8-Core",
    "images": [
      "https://by3301files.storage.live.com/y4mgExYw_2bfKp-XgiOaVkzKR1IWUgE0P-kpxujiBphs9C4DiLPWs9OcPtD8TpLFdZYtzf77ch_pUJQcKbr4Au6JGYKNlhK5HPVCBzKUaoxhVUYG07B4jkCUW39OI0BqYO3h2ra9V9x6-PoJdOsYDqYQHbosM6_7PgTytwUXUzL-azfaPzS-IGjVKEUIdYItN37?width=858&height=933&cropmode=none",
      "https://by3301files.storage.live.com/y4m-AfVLckUo5VQLGfmgCkclRqX_dgX5mqVHcVpGlRpv1QKIU9R1o-jOYDNwwQiwDOeJIznnyMzvCu5mzydmyfnX92KcUTBhGgRiBmhKvYFT88Bkiyg7TO49edGDUWxcp_HaB8NNcvcVrSg-9oW6gUgIvxyeq9vnz3bfkZAuUmZJBo3LvBUQiaHAofDCqWjEs8o?width=421&height=422&cropmode=none",
      "https://by3301files.storage.live.com/y4mfTaFQbgIoGioY19fH7NmCwj7oB3iaQGxWhiax8Bf6YRCWg3e9uhs-Y0y9W04enV6bZ-VwWKew_RH4NZPw_BpUZQ_Ut3elCOjwttEGwCM2Ja65AptlB7PONk_a0aYcTKuIOmid1yUVqfdiTPf73mpS_5v4nxOzRQrGX9aBnFd5BNFbrzqJFF0fjv6pJEPyGrO?width=868&height=927&cropmode=none",
    ],
    "price": 332.32,
    "stock": 5,
    "brand": "AMD",
    "category": "Processor's",
    "description": [
      "Play some of the most popular games at 1080p with the fastest processor graphics in the world, no graphics card required",
      "8 Cores and 16 processing threads, bundled with the AMD Wraith Stealth cooler",
      "4.6 GHz Max Boost, unlocked for overclocking, 20 MB cache, DDR4-3200 support",
      "For the advanced Socket AM4 platform. Maximum Operating Temperature (Tjmax)-95°C",
    ],
    "imagesDescription": [],
  },

  // Mouse

  {
    "name": "Razer DeathAdder Essential - Gaming Mouse",
    "images": [
      "https://by3301files.storage.live.com/y4mHXhNO88zXONr3Bjq4y0x6Yodped725W_aDh7WQi_cSWSnbShppke9mXddY7lrCOSJXtbzJ0M3-T-XJEXs7TTLkO6X5pZch7G6RbtDOnCSr0a0ZF837MuNPQga9D9rLs-_5iayYQRd3zxV_pwoBedl9w33hYsz_JNVdzx4FsVBfxQdyqUS2bA-t2OZOJ7bPjo?width=932&height=1323&cropmode=none",
      "https://by3301files.storage.live.com/y4mojw_4iA2zMOkMI5QtkC3QvddZ1Jaou8nuvjM2hXmcQT4p9GQiZI_05O-FRs1FRx_l6Q9BkR5VNCBLnopFGQ8QYvM_bP-Rv4qpFSeyBOOZkocCKMOFNz9bbJ5hOdN1h_Xer-p9efTEuwCs1h0FUWaGbO03TvYN4GKiH2T5J0N95MG6nInskw_MdbJnpcUxmLW?width=1500&height=1500&cropmode=none",
      "https://by3301files.storage.live.com/y4mNVqTAQ6X9QnRmtgUvYU1w6bQMoCQORdw7l1bab01ZzYjkaBIpAgDnyTHVRpnsFnMTZxoWpAhLa42VR48t2C6NAxw6RG0gWNL2W25fKo9lArjTcD_iCwyTAiAzpnNdL_aVlapqvtWuN3ku4IJkg0m70ZBEEYaQyVHC6SxcVb971S8gbnFLX8I6C5mS_tNxr9f?width=1500&height=1500&cropmode=none",
    ],
    "price": 23.66,
    "stock": 7,
    "brand": "Razer",
    "category": "Mouse",
    "description": [
      "6,400 DPI High Precision Optical Sensor - Offers on-the-fly sensitivity adjustment via dedicated (reprogrammable) DPI buttons for gaming and creative work",
      "Durable mechanical switches - supports up to 10 million clicks",
      "Rubber knurled scroll wheel for maximum precision - small tactile bumps increase grip and allow for more controlled scrolling in high stake playing situations",
      "5 programmable buttons - enables button mapping and complex macro function mapping via Razer Synapse",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Amazon Basics Wireless Computer Mouse with Nano USB Receiver - Black",
    "images": [
      "https://by3301files.storage.live.com/y4mTDK4y4JGrKUFbdmJ6k17Tb-gQAtphwgnD8u4Xna1iYBp1SJqW4_KYANvWMnjBiu9fP0KyAHZ9KuTFf6ysfs4lrIJu5Sagf0GrOGxn1YLHZl0_0PzVh5L_4DZC2tOFIsno-ytzpOE4m20k8EzUY71Ggln__-PEkHLbc0yLgDgTMpdGYuPnYMZGgclSujw0Fcm?width=1465&height=1465&cropmode=none",
      "https://by3301files.storage.live.com/y4mYbvM_fjsXeknePZ9uuofb9FW3DSVSIiq7Fa_3tqoNSwOhs2_4Wd1-dqw5j9zkvDHHxpjOJX54yGIAaAUmHbV0AJTMeNIVFOv7n7swJAf-XW8RVfiX7KFG6644Wv2jzHDOIjc4pNMb6-GQVrCYWV5xqYw6ZVE65vuQJlR6rePvpyoK5acXmbyp_GBFjsx3Y-6?width=956&height=839&cropmode=none",
      "https://by3301files.storage.live.com/y4mJ-50gTtRExt7uMmSpvDYUM-6i-joVSyN16U5pV5THaxA_TQJkdXwI-8ThGIz9UJukgo8kIUKZc_0XATCc_B5VOmrG7AtpNt89ODbNdpGf390DktjHjnA8NVHNxO14PU9pu93EkWPOh2y1a5lMANbCaDRYvvazaAf6C8vNCEw6R1yZ5r4zGYPA0Owsy3UOXBx?width=944&height=1058&cropmode=none",
    ],
    "price": 12.19,
    "stock": 5,
    "brand": "Amazon Basics",
    "category": "Mouse",
    "description": [
      "Smooth Precise 3-Button Wireless Optical Mouse with Nano USB Receiver for Laptop, Desktop and Netbook",
      "2.4 GHz wireless (not Bluetooth) provides a powerful and reliable connection",
      "The nano-receiver stays in the PC's USB port or stows conveniently inside the wireless mouse when not in use (Note: the receiver is stored inside the production mouse and needs to be removed when setting up)",
      "Compatible with Windows 2000, XP, Vista, 7, 8 and 10",
      "Easy installation - see user manual for instructions",
    ],
    "imagesDescription": [],
  },
  {
    "name": "High-performance mouse for playing video games, Logitech",
    "images": [
      "https://by3301files.storage.live.com/y4mYWW4-3iypCgTMNipI8-L00v5ku1NNNUa8WblzUnTEKB2B8RnEwbt006h0DA1nlq8CDz8wRbXP4jCZCFiiVmpc5A6oeTjBfxCW94XJiLrboiKdEeQfQY9oCLKUqU85051068HtoG5ZFCJpCZ2N47WJ111sHkmkHuvFxdDMA8VclVdSmCA-53Jksb0-vdcrsrw?width=1380&height=1327&cropmode=none",
      "https://by3301files.storage.live.com/y4mq1QdezboNKdpQqo2zA51TOpH5prpEDV7tSyt5_i6vJ8zIH1grzAvPdWyNgt0kJfWWuRSKW0mMeMnlJSvGVAQ4IO_OWpybnQ9IfV3V3aGbc4V8CsuNBArHpcTANlUFD9g0E_9JFNbG8Bv5bGCCsf7EMbK4o5lAgfYPfvXcY9VLvjJ94pKNkIg6g7n7_nriIVy?width=1482&height=857&cropmode=none",
      "https://by3301files.storage.live.com/y4mGG49kC1RhcpKWdeY2uQBf8BYCEukHR2R3ZFPxX4AGlocspGsW6tgaNpxELgmIbNEnAJDqUGHBhxSWXJmRUQW1zXjdA8B-JVAvJWfdRyJ3RY8fyWsQqcD3ttFcIsWfHOiVhWhkdEGp7DgsESLWLewN4yBpEp8SFJK5N8cQfjP8RbPTam3cBBxcUUwIZzkNf-G?width=1500&height=1500&cropmode=none",
    ],
    "price": 21.99,
    "stock": 7,
    "brand": "Logitech g",
    "category": "Mouse",
    "description": [
      "Customizable buttons and built-in memory: 11 custom commands assigned to the buttons and save up to 5 profiles ready to play directly on the mouse.",
      "16K Sensor - Logitech's most accurate high-performance sensor, with up to 16,000 DPI for maximum speed, accuracy and responsiveness across the entire DPI range",
      "Mechanical Switch Button Tension: Metal spring tensioning system and built-in pivoting hinges on the left and right gaming mouse buttons for a crisp and clean feel, with quick click feedback.",
      "Adjustable Weight System - Reach up to five removable 0.13 oz weights inside the mouse for custom weight and balance adjustment.",
      "Programmable RGB lighting and LIGHTSYNC technology - Customize lighting of nearly 16.8 million colors to match the colors on your computer, dedicate your own colors, or sync those of other Logitech G equipment.",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Razer Basilisk X HyperSpeed ​​Wireless Gaming Mouse: Bluetooth and wireless compatible",
    "images": [
      "https://by3301files.storage.live.com/y4m7W6HFmYDaUhIiKMqijUj8UjLAyPC6vlL53e0quiceWLIU-QeZXJ3ZBR-vwBO1CvCjN10RQ1NNj676XDDgybWWSCbyyXqcpVeMWogO3dOAvNEWJA6LYNADo3sw72uMlPp9zsk-fIR40HwFp83gX63dagecBi5Fz70hrQ8qdzrm0kN99YTMdnkX9CXgxKpmmQ-?width=872&height=1500&cropmode=none",
      "https://by3301files.storage.live.com/y4mDthNSSmYnO16Cj6C_wweJAxhAlfxOjCVb-5-rmjJbINrR57NvSU1K_FU6D_s9qqyAGSH6X9dtsEJT4Pdw3B8bHpfc1CUoJ3ij-1-TKwWe7gKELJdVdukH9ZOxeBHR-u5mC7x2Lz32DmacWt3Nomk52u6MqXni9c9haKzoNd5VTg82d88VDYoIIlvRN_6YXtk?width=1500&height=1500&cropmode=none",
      "https://by3301files.storage.live.com/y4mGzqDq1f6MXHKrcknvrqPeRKlJTWIvzUsEoryNcrhqvuQ6v4UcAbOd7GWbDjt6csiIL2RpXmWe2i8-GviI_LH6PCS4o5yzWIR23fLcREqDgKLfqQn7DqZWy9oPGJ1A_2wt9ZT-6Zo8DHfkYr4tgTNuGaEEW7Xii16osguH51SnvQSkdOwKdz-OpUyOJzYXF0w?width=1500&height=1500&cropmode=none",
    ],
    "price": 35.98,
    "stock": 7,
    "brand": "Razer",
    "category": "Mouse",
    "description": [
      "The most in-demand video game peripheral manufacturer in the United States. Source - The NPD Group, Inc., USA.",
      "11 programmable buttons: Allows reconfiguration and assignment of complex macro functions through Razer Synapse 3.",
    ],
    "imagesDescription": [],
  },
  {
    "name": "TeckNet Pro 2.4G ergonomic optical mouse with nano USB receiver",
    "images": [
      "https://by3301files.storage.live.com/y4m4tlhlVoYJwooZDYqNKSD8cJYiDR76BukXFBCn4FfLvkztn4Inzq7gotE1lCqX6tQf4t6O_OAh230iPTjN_KQC6CPD9VtpKIueyrSlinyhMowRtuGft6wm0NywYrNqTBIX2TnICtwLB_1L62cgptsT3fNUKviFINS9bEiwI7bOvIhnkBcu1om_-AfDpCfrEF4?width=1300&height=1476&cropmode=none",
      "https://by3301files.storage.live.com/y4mb57dXobokFSxZjwW5QpqaWROVhMPZQfEh4MfT3VfWj-Qk3UG88xWckhlHh2NONBXuAhHR6K2fr0u6kMDAp-wWmibMw9dgTYcpvQe8JMlliIYugfkqppH4iT-GPxLx-DYFGcRljNmqP_5KBiNxg_cZ8H-iUaifJb8JkiZZpXIxJYIUfHZw-K4Yee-ZgnT_y7T?width=1284&height=1422&cropmode=none",
      "https://by3301files.storage.live.com/y4mtL2NSSq79pSV7xg5q6U5hazH9GjKlqFXarfdZschnZYje9YcnWs3LpLmwO9bKZHcdZ8bzA2dNFEQO7HWXuLxAvshO519tbryGp70w3QOgRTc5eygnYiSXME0fGD6HKec1uFRbz7ePA_cRLMhX87iw6-PnUWMc5eOJG6mwZc5GAspmXqvQAyWBQ53fMivUnuP?width=1000&height=962&cropmode=none",
    ],
    "price": 11.99,
    "stock": 8,
    "brand": "THE SIGN",
    "category": "Mouse",
    "description": [
      "Plug & Play: includes a small USB nano-receiver (it stores in the back of the mouse), just connect it to the computer and forget it. 5 adjustable levels of DPI (2600/2000/1600/1200/800): choose your own cursor speed.",
      "Hassle-free design - Up to 24-month battery life with battery level indicator. Automatic smart sleep mode (battery life may vary by user and computer).",
      "TeckNet Tru-Wave technology that provides intelligent and precise cursor control on many types of surfaces. TeckNet Co-Link Technology - After connecting, no need to reconnect after signal loss or shutdown.",
      "2.4 GHz Wireless: Ensures a reliable connection with an increased operating distance of up to 16.4 yards and eliminates lag, drops, and interference. Contoured shape with soft rubber grips for all-day comfort.",
      "Compatible with Windows XP, Vista, 7, 8, 8.1, 10, Mac and Linux. Works with computer, laptop, Chromebook, and more. (Batteries are not included.)",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Bluetooth, Wireless Rechargeable Gaming Mouse, Multi-Device + Side Buttons",
    "images": [
      "https://by3301files.storage.live.com/y4mhIcsbNswBppn4hjQz2recnLLYQBp3xxE68lbnAzSbD7O5OA8YgH2UKNomqde_RHFdrayryHEtWFQqeP_oajGWlvxEYAwJNkauLflUPSY2PI6kwYPzPeg3B590urBPDTCMJgaEKJR5Kp8K0CcODoEO_mSV66qb1T7jSgWiHOKcWyndRWagzB8QEbTRRYTFJH7?width=1500&height=1470&cropmode=none",
      "https://by3301files.storage.live.com/y4mUiFx9tPi4cxQeckxucPJECZ5V1j4sYlxxBeFIKeWm3jP7cP450WR5u60dfl5U8kjU0VqkhZCpL19yqu8T44v7-2k8lkCYroaaeygBE8y64l1A0l_8wSesUG5Zh0LvmWQK4Q3eRDmK5FUDYL80WW4jQXT4TopjZ-XEhDKPwWtIpuLa8wQulL0nAHi074niDeA?width=948&height=924&cropmode=none",
      "https://by3301files.storage.live.com/y4m7RRmd9gjuansdDfB98Bb4WcWpd-W_nJWHOdTpmg1OrPc-QqWvYUG9eOzT9FTo7f1KTF8Ydxy-Dxa87aGuOgkrp_fwTqwqIi9dVWsO7xf-DYnap_hrtZSO83U5EjmHnR732_ETgDF3ilYkMxXSP51aSQaUQeA3iaEQIVIWdNy7F8ZYsOlFsINO0Z8dRJlx5-M?width=1001&height=1001&cropmode=none",
    ],
    "price": 27.99,
    "stock": 9,
    "brand": "SHUNJINRUN",
    "category": "Mouse",
    "description": [
      "The AULA SC200 wireless mouse can be connected by Bluetooth 5.0 / 3.0 and 2.4G. Connect up to 3 devices like Windows computer, MacBook and Android tablet, you can freely switch to each mode by clicking the mode switch button. The maximum operating distance of each mode is 32.8 ft.",
      "Rechargeable and Portable: Built-in 800mAh rechargeable battery, easy to charge with included USB cable. Adopt smart energy-saving design, standby time is long with automatic sleep mode. The mouse can be used while charging, so there's no need to worry about the embarrassment of running out of battery. Built-in 2.4G USB receiver at the bottom of the mouse, convenient to hold, slip the mouse into your bag and take up a small space.",
      "7 different color changing LED light while in use, make your mouse multi-color and cool. (Note: LED lights change color automatically, and do not stay in one color, it will change regularly with 7 colors. LED backlight can be turned on or off at the bottom power switch)",
      "Strong and dominant appearance, double wing plating, touch-friendly material to perfectly fit your hands, long-term use without fatigue. Fast response, stable refresh rate, smooth tracking, precise movement, provides a fantastic wearing experience. 3 adjustable DPI levels between 800, 1200, 1600 to satisfy both ordinary game and work, easily change the cursor sensitivity depending on your need.",
      "Professional Beken RF IC chip provides a fantastic using experience of fast response, stable refresh rate, smooth tracking, precise movement. It is compatible with Windows 7/8/10 / XP / Vista, Chrome OS and Mac OS. (PS Bluetooth 5.0 supports iOS system for both iPad and iPhone, but iOS system has to be iOS 14 or later version).",
    ],
    "imagesDescription": [],
  },

  // Keyboard

  {
    "name": "Razer Cynosa Chroma Gaming Keyboard: Individually Backlit RGB Keys",
    "images": [
      "https://bn1305files.storage.live.com/y4m-zgZMk9v-frYE9TUN16zKbgKUrBOar7tSDB9SONwWXfve4k29XpSpPeiNDKxiLBPJXBq7jkwl_G_AxBGfywMkWg4O3s5miRZ9neifj11Qa2VLzKOjut5dB6uCdECEE90ooss8bgxpNofBWHTmpC_4WGnh1sMyqrV8LfoMKUjBfOK0hFIjW_xQwr6O2tPkE5w?width=900&height=442&cropmode=none",
      "https://bn1305files.storage.live.com/y4m4dNm8eDs-MSI2MNvH1aVwvzBOqwGbL_5y_mA3WyyX-1dPcDi1385MbL9qAriSAcvzi2AYEDh6MN4fa11kDFPNyG5NkJwhJL8Ua9vvdbyZsjsf-KPnEL0QbF4KSDqYHbJo8kI8d9xDJchwXbfSvKUr8dJrVgYbQiHtXfoCyULdLHF4MZ3vnEnKcKW3Ti1_cFl?width=1000&height=1000&cropmode=none",
      "https://bn1305files.storage.live.com/y4mwfladjJ7-lYs8Rav79fZP0YpWdlkDyyd14WvhvPbiENenCdxmqrSMKrMrrW6S49joBuAcHIPJi25-oc0LY5VCkbi5RRt4vx4aWo0vkvK5SZzj1H3VJMyTDSIpW4-8TACiMWGWeSepzndcUHF-oqNojAHZo9tEYWxG0ObcMLrgyfE3hmAUgxnNzZLQWy6_CDA?width=1000&height=1000&cropmode=none",
    ],
    "price": 59.99,
    "stock": 24,
    "brand": "Razer",
    "category": "Keyboard",
    "description": [
      "All-Around Gaming Performance: Able to execute up to ten commands at the same time with built-in key rollover anti-ghosting",
      "Ultimate Personalization & Gaming Immersion with Razer Chroma: Fully syncs with popular games, Razer hardware, Philips Hue, and gear from 30 plus partners; supports 16.8 million colors on individually backlit keys",
      "Spill-Resistant Design: Built to withstand most accidental liquid splashes",
      "Fully Programmable Macros: Razer Hypershift allows for all keys and keypress combinations to be remapped to execute complex commands",
      "Durable Construction: Supports up to 80 million clicks with a 2 year manufacturer warranty",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Logitech K350 Wireless Wave Ergonomic Keyboard with Unifying Wireless Technology",
    "images": [
      "https://bn1305files.storage.live.com/y4mKLQwcLS_qtpbuj-XW3f5JB4IxN8PzHShVHXkx8pN8jkxqIKSvZPFe8qGqua7SVCs8A1wGkd5EeP4ov5VHXBwBcTOaPLpwfRe2aAj92eMn9P8-Xn_ZU2CoMSuYW_T0klAPQZAKVBRRW6UR7YA7Q5k37ypA7yg7b6GkNdje3dGkojojwO39XUEybA5iNeeVS1v?width=1500&height=810&cropmode=none",
      "https://bn1305files.storage.live.com/y4mpEIJ72u6wU9Y88R1r9x4apmjX1TStc92N3d11GJ1MfNaI4S3-qEH9pyJmT2C43F-iXg-IWtXipkNC3Qev2IWcPwxi_jMg5F8D2Kon5DWz80hcSK45dFKBcboQCmWSH18xAITrT66V3ePCDiosO_xZsnjfVUSyBx783DLF4l3XfSn2O9uZ7elxcLC-6zESFOe?width=1500&height=669&cropmode=none",
      "https://bn1305files.storage.live.com/y4mHvWPyVnpNLzlUMDEHEU3oW1F7M6fpY_OiKMHLoF8lLAQAQNA4F6xRY51HKgDcdhGPeFj3mxnXeR18U2QkOTVu_l0q21oRLh1NVISESr7oD3u4PRVogWDvxAuzTKl1AkiStFGpB0Ptqdso3AFnoqYaaUEzrK47DUK7PAakO8y-egTBfpxI1gnQYlJlZtsKz8c?width=1500&height=992&cropmode=none",
    ],
    "price": 29.99,
    "stock": 32,
    "brand": "Logitech",
    "category": "Keyboard",
    "description": [
      "Wave design with Constant Curve layout: Curved layout guides hands into just the right position",
      "Ease and comfort: Cushioned palm rest makes work easier and fun more fun",
      "Longer battery time: This feature gives you up to three years of battery life",
      "Logitech Unifying receiver: The tiny Unifying receiver stays in your notebook, so there's no need to unplug it when you move around",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Apple Magic Keyboard with Numeric Keypad (Wireless, Rechargable)",
    "images": [
      "https://bn1305files.storage.live.com/y4mCMBj5Fm6j1FFvQKe36Q_O6ajsEuQzyNw3u09YrWG5qdMuQhMqRBZttEUFqGBMZD57bQ19LLPNeArmliqHzKCo6Afkuk_mw6bBEzDuBaGa97bTd-zVrv6YFdBHrMc1In7vEm8Hhz4XvJLrG3Q5oj1kPOzeftjtBjqWGx_HFRU7xi47VllGpAhXOCW2J0eb9R9?width=1500&height=411&cropmode=none",
      "https://bn1305files.storage.live.com/y4mgj5eO3MTg-bxv4564zZvcsacAAz-Gy5J5IP87Ft3MYnHLuxRRGOKX5l3tmQKU5ffAwZofJDmrP7hNUFba_bAZ4nnMuhKZn7EerwOilc4wFWVR6MsZPxuYvpO2CyIf9Ga1lqK5HS0k7XlkYaqVGwivo12dKhsq_nIpaPXiOWQGh686UqZWS_4ks7G5BdTEfAh?width=1500&height=171&cropmode=none",
      "https://bn1305files.storage.live.com/y4melHl9wTGtO9FySnWWEXg_sAwPjBRipYGQgUzEx_VdrlqOMj95aQQfctQoYxbVu3hDB0lW6IDTaRuVOsiTNjXNyAMi_i7i8JwL2dihhjSlgUWl6e1fo9kT-jQjWJpskMhlLIvZb09b5Am7qWYnxFcrAnuAQrMMlFTMHPk_0c2GsLTwj1H389Hj1oFmzqXKJQW?width=525&height=1500&cropmode=none",
    ],
    "price": 129.99,
    "stock": 7,
    "brand": "Apple",
    "category": "Keyboard",
    "description": [
      "Magic Keyboard with Numeric Keypad features an extended layout, with document navigation controls for quick scrolling and full-size arrow keys for gaming",
      "A scissor mechanism beneath each key allows for increased stability, while optimized key travel and a low profile provide a comfortable and precise typing experience",
      "The numeric keypad is also great for spreadsheets and finance applications",
    ],
    "imagesDescription": [],
  },
  {
    "name": "NPET K62 60% Gaming Keyboard",
    "images": [
      "https://bn1305files.storage.live.com/y4mJqQ5E4VIOPT8talLwqShUbsO1Fqqn-63w322ndxWziwIXYFyE5CjhWBULDcBcwNUNEn5jUTsFrX_tDmGo9HT_OZ_FnUjXgtDUw84HM4hDVpiEJMWLny7VoiJPx0BbFljOcBDeL-VVYxf7trUnP6k08uxCksM5g4GJG126PM32sB8U1boqxgLIVk5kJ087GVC?width=1500&height=510&cropmode=none",
      "https://bn1305files.storage.live.com/y4my4Eq2vLmxQFuCs8ItITxzxEz2dRM-V4l_PiYlhTP_aRpE4YkCgZLCbSIwyTrFBzhGZZefYX3TVaTheQF_5iklCWyngeMZk2e1B0uB3zqddxJrxuP6mMgQGqDIsZqwOuF6LoxKNb1fCS8pBF59VDsB2qBSvbCBD3lTtiUXumrVr9yhPAsSq1zh6IJvvp842NQ?width=1500&height=1500&cropmode=none",
      "https://bn1305files.storage.live.com/y4mWjWlmMxCCko1FHZ77DwfkeVe_mR5Cnp6zMr3zlQNE3ddnxWCOWvnl7H9eF3nXQ5eiE-xNVx5Xw87XyJruTgtyG7bV3CpQ3S8CvLfxrzdJqEaqn4qi9bHdUD5cglxUiDzYN4Kyha2pBbPy5c9CA9ddJfWvw5U9fSoPZm36l1eFL2Vke6OsHbA5PvsCFnd_JLP?width=1500&height=1500&cropmode=none",
    ],
    "price": 20.99,
    "stock": 27,
    "brand": "NPET",
    "category": "Keyboard",
    "description": [
      "Durable Keycaps: Precision-molded ABS double-shot keycaps with a standard bottom row layout resist wear, fading, and shine",
      "Compact Design: Ultra-compact 68-key, portable design with detachable cable. Secure connection and safe transport in your travel bag",
      "Ergonomics: The design of this gaming keyboard is based on ergonomics and with folding stand at the back",
      "RGB Backlit Keyboard: This RGB keyboard has 11 RGB backlight modes, 7 single backlight modes, and 1 full rainbow backlight",
    ],
    "imagesDescription": [],
  },
  {
    "name": "UBOTIE Colorful Bluetooth 100Keys Keyboards",
    "images": [
      "https://bn1305files.storage.live.com/y4mk_l5w-WhDitLUMmUoEUpf-NnujwAh2Yi_CO17I9ZMlnOvCzuyyJTgI2-8IlDgF-k_ROIwMzbxWk11YpuJfTmavJu2BFOFoax4397fYKOaX72vpnvXc4v6TbdZYmJ_gG9iIkcykNtqWEVuGdHdf6rj9qju5POQuRO8IFwqP-HxnGkdPKuQlSY9Aud225cSWJG?width=1500&height=522&cropmode=none",
      "https://bn1305files.storage.live.com/y4m2vl1ZyW-THmz1E94_0ND6AA0qZIZdf4R7sLNBCveNMKSSZVEOmPf53iD0U0ZiOSVdamJ53WqEq_ye-P2fHulUMRRMgvV8ZfsU9MiO6URLIt034MvDnRaqSM48q2E5BMZ77ABPGbmhlMtxyEsaCbg6qdvKjY6As-snV2UoW0_v2NlsEtRHMlULp48Ys9ESg11?width=1500&height=1500&cropmode=none",
      "https://bn1305files.storage.live.com/y4mkyeBD2CWdW8givL9X7LzL6pauCZEh3W60EYw_KuoPOKoHKNzQxOA5obOV_Cfax9sGbDGIhfrsPNUsNMDPeHNQZaAMoD8fgilmcr3nAmefG7xpmLXLFimLqkqRFjf4VZSruk81WYDLKbfN8XztUCoa5YDOKzeG_0VEMsRqtkHmr5UokaIJwneI-nVRuZf6N7F?width=1500&height=1500&cropmode=none",
    ],
    "price": 39.99,
    "stock": 42,
    "brand": "UBOTIE",
    "category": "Keyboard",
    "description": [
      "🌈【GORGEOUS GRADUAL COLORS & NEVER FADE OFF】",
      "🎁【RETRO ROUND KEYCAPS】",
      "🎈 【COMPATIBLE WITH WINDOWS & MAC OS & IOS & ANDROID】",
      "🎀 【STABLE BLUETOOTH CONNECTION TECHNOLOGY】",
      "🌈【ANY REPLACEMENT&REFUND WILL BE RESPONDED IN 6Hrs】",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Keychron K4 Hot Swappable Mechanical Gaming Keyboard RGB Backlit",
    "images": [
      "https://bn1305files.storage.live.com/y4mEjv_DnAYyhqUp59l5wFIAsKg2cW5BLWFr-HQL80kIrNsQ9dsNtHRVLI49cTD8rZ6adzBdmUc3zoYIBhCALlbwOANA_gUS3UOZCpIYOcVV1HmfgCoqfQ0tbzi8s7JQtxqWg2ykfTM5xO95myZAJU9ViCunZ0Mrk33BZ0I71LTikFe4uBPhbUf4ZeKEGv9QiX9?width=1500&height=513&cropmode=none",
      "https://bn1305files.storage.live.com/y4mshbeEvMYz-6ftFc9hX5hegYtbSWvqAyHCiw86IP8XAaM3fNL9I42SqYCE_TM3PPF6XcZA8tfJTruq2JX7IXpzLi8A0ueUZn4Pw12_14lQQjvK5gAZM96-nwjPbdCXt9uYdTU2jgt01_3NejJ6dBjdFu7mMpYu0mK05YZystZN0fFaFJhnUKeFy_w1GReSF3p?width=1500&height=1500&cropmode=none",
      "https://bn1305files.storage.live.com/y4m-e4aZ5XG9kE2695jNT9GrBDMMUv4ZwdTdsq3sCe0rPogn7QQuaKnE_ZIZXg5WknbXeX9vU0uhMo88b5O-AulajYOMubJwPSzrLL4RSIxHas0FV87BVPmLkn2YUO3757wpaJ_HkJwp0tJfgHqRWAAHvib25GX6-fYDkSren7hLg7Q-jI8xfzbRFc5wcJovbgj?width=1500&height=1261&cropmode=none",
      "https://bn1305files.storage.live.com/y4mqwqyseTzEDwCG2PRMsdFY1RJbV8NlwpypeQyvRAqWSv1bis5mbwgLM7lvajHWzUNuaxp98rvm_DlvyG5KHB1xtMfOd2GlJDXaZ8lXui5VN7Gr8ouKb6ZgukHWjwynKkXA97_LjDzYcnmNKXs-wfALnZfmKzUMfcaV6t2LS6KK85Kt_HqAY06dcVs1V27vqVC?width=1500&height=1230&cropmode=none",
    ],
    "price": 109.99,
    "stock": 12,
    "brand": "Keychron",
    "category": "Keyboard",
    "description": [
      "A hot-swappable 96% layout (100-key) wireless mechanical keyboard with aluminum frame",
      "Connects with up to 3 devices via Bluetooth and switch among them easily",
      "With a unique Mac layout, the K4 has all the necessary Mac function keys while still being compatible with Windows",
      "The K4 can last up to 240 hours (with backlit disabled) with a 4000 mAh big battery, which is one of the biggest in mechanical keyboards",
      "The K4 gives the freedom to customize your typing experience with its hot-swappable PCB",
    ],
    "imagesDescription": [],
  },

  // Monitor

  {
    "name": "SAMSUNG LC27F398FWNXZA SAMSUNG C27F398 27 Inch Curved LED Monitor",
    "images": [
      "https://bn1305files.storage.live.com/y4mn3qLccURTsNk3zG2t6L71AhZlQar3WAZ4Xj4HjvFQd-IIpxjNBNvnJPsMLIVRWEwAI9w_j2hWReKMFBnXlPUQP9vrnXvQH2XCd9jBXFOkKZK8FeaaIftmhs4-NSxYUU_fVYRWXIYUYDjtLJp3LfQWocKF5U8-3U0EUdRSg2wfNVZAUVge-uuGCuk_rdY47Qv?width=1500&height=1387&cropmode=none",
      "https://bn1305files.storage.live.com/y4m3pk5T0Ky5_YKHTH6S4yRHVbrBVi73ogsDatlqh7pzpzphAyl4fXjw_7LYUxRukueBdwC68clt6xNcgV4x7HEIYnLW6P7TdHf8Jm6o4N9lcpwzI56DwjQQRmZwfTU0NvtIOdXKPF4KVxfP4srl-Jx8spS5twsVn-Smh54oK8wVdVSTsr1v8yssDNHU5uvIkYP?width=1500&height=341&cropmode=none",
      "https://bn1305files.storage.live.com/y4meij1t8HU4qTva2pvr_mPOgcfJwY1QHWsstF2noUN4EGU_t2hMHvWoK-aiUnUqMGfnqOsNsz6bDGhs3rXBRNtP9REdZgqaziQnJgLxjUvADs3t8ZulZtE13rlD3KhUuquCmbqe_7AbyKeJ-CFqlCryVT9pi9BWj2X8leQ10COUq3tYnUuRQLuly_MXsaSVWhG?width=1500&height=1172&cropmode=none",
    ],
    "price": 199.99,
    "stock": 32,
    "brand": "Samsung",
    "category": "Monitor",
    "description": [
      "Industry leading 1800R screen curvature for immersive viewing",
      "Easy setup process, leveraging inside-out tracking (no additional tracking equipment necessary)",
      "Rapid 4ms response time for a clear picture during fast moving scenes",
      "Color gamut (NTSC 1976): 72 percent, brightness minimum: 200cd/m2; Windows Compatible: Windows 10",
      "Product Dimensions Without Stand: 24.5 inch x 14.5 inch x 3.2 inch; With Stand: 24.5 inch x 18.4 inch x 9.6 inch",
      "Refresh Rate is 60 Hertz",
    ],
    "imagesDescription": [],
  },
  {
    "name": "SAMSUNG Odyssey G3 24-Inch Gaming Monitor 144hz",
    "images": [
      "https://bn1305files.storage.live.com/y4m1ZmnvlL4VHlkhudxbRmYD-bYaYQ_hj-aUdfuKcw721CdBrgTpeNGAIvLJqOaP3iQhK3j8LIIe_yuUmGw5aiAWbUerwPKmiZ3xURvoNxVyYhI5Ju9Urr85YAe0_7RJW15-f9YhUghCK4kSA_b-9XmqCSH7uz6oaimaeMWL8U2-GGRwO2U_GswZJhzUjv8D4yp?width=1500&height=1338&cropmode=none",
      "https://bn1305files.storage.live.com/y4mH7NwzLJsU5oRBcRhLocizqEpPkCr-yIGulWp1ZOijPCeXy5tK_R72tJuEXKRtGupBmEQgZqH_JiYKjr2VTb86nooUHH8YeVB4sz3nRKIIprYDn5YAl_SxFvNUUN0M4qy9nEzPWR8tJ-kS4EaLUj8hSt5lQX5HeGmczRtZT_ugYEvfqzUAL24g7LojVpwGRa6?width=1500&height=624&cropmode=none",
      "https://bn1305files.storage.live.com/y4mC3BTu3pR2S5s0Opq9l6dEI7D6aeyTHICg7gDcXGJ3wz6hZ05NXtAN8NiErr9OoeG_Nl8jeqRQ6KlKg-J6jWBZ0I-KZpa5bZIVS-h6i_aRTuUo6TqmI_3CzGXYjMbNTpIYEyGQMNt_dGXctJkt4yml276QOfYK-lNx5ca-dMLsGsJ6Zxp7qEpQGKUbM-aFfFm?width=612&height=1500&cropmode=none",
    ],
    "price": 279.99,
    "stock": 25,
    "brand": "Samsung",
    "category": "Monitor",
    "description": [
      "SMOOTH TRANSITIONS: This vertical gaming monitor has a 144hz refresh rate and 1ms response time prevents motion blur and creates a smooth gaming experience",
      "EXTRA CLARITY: The FHD resolution creates a crystal clear color with an gaming monitor that provides a wide viewing angle",
      "FREESYNC: AMD FreeSync synchronizes the refresh rate of your graphics card and ultrawide gaming monitor to reduce image ear and shutter",
      "VERTICAL MONITOR: Adjust the height, tilt and swivel to a position that suits your eye level with this vertical monitor",
    ],
    "imagesDescription": [],
  },
  {
    "name": "BenQ Zowie XL2540K 24.5 inch 240Hz Gaming Monitor",
    "images": [
      "https://bn1305files.storage.live.com/y4mTw5LcLq6yeJYNBxYRVVCQqqDj9aABsBZGyTqQ6xerWt0ZwVfLDoKF0IbaIo_RfAN_MvWVTHzL1TGfF8N3ZxEQkXLDEjf1HcHaPr76mxvql_rTLVexkAF7xrODWmhL7JbvfnK4aw1HrzUEym9mydTrWj4w1Z5q0bSnugQCg47qqRiukZbGCZIJtsjL-c66rNc?width=907&height=757&cropmode=none",
      "https://bn1305files.storage.live.com/y4m9LNoqQBmJuCAsSBjQ6VVz62vQwGKlDU1o6WBCvSJ-3SAtA4LSCDMHx0sELakFUxLMxRkV3Z9iV2722l7jY8r4mZvuvAwGdZ4V5wUeW1oHm1kcslJtSO3qFC-F2bJZtJ6xqr6g81iQWBQMrMIA3ZD_MwXf3qL33MNF35Xcyys5KRljLz2ktDEZh-oHgadMdYt?width=867&height=858&cropmode=none",
      "https://bn1305files.storage.live.com/y4mCFBYj0WmxqTnIwVyEMsVNZI1Zf6t4MNDTyg_ek7xHvnYZNlCbrdLy0g-fsrqzOfzliC4ueAbbcXp4Oqkqd3TFlgbApfo1U_f_8KC0t7DTg_dqlUUKT3m9s5h7rxxEdMqB-cqWOzO1oCtp71RxtmD0FPyJz5wAMZR9WZORmOzIL-ZmDo_fAmZQO2ny4TbhU9A?width=838&height=938&cropmode=none",
    ],
    "price": 329.99,
    "stock": 48,
    "brand": "BenQ",
    "category": "Monitor",
    "description": [
      "Lightning-fast 240 Hz high refresh rate performance for a smooth PC gaming experience. 120Hz Compatible for PS5 and Xbox Series X",
      "The redesigned base takes up less space, allowing gamer more space in their set-up for in-game movements",
      "Increased height adjustment range and free tilt design provide more flexibility based on your personal preference",
      "Share your setting easily via XL Setting to Share; Customizable Quick access menu",
      "Color Vibrance and Black eQualizer technology to enhance visual clarity and customized color settings.",
    ],
    "imagesDescription": [],
  },
  {
    "name": "ASUS ROG Strix 27” 2K HDR Gaming Monitor (XG27AQM) - WQHD (2560 x 1440), Fast IPS, 270Hz",
    "images": [
      "https://bn1305files.storage.live.com/y4mNTxAOqsTC8nNBWTJttuEtsZF-P2q-psW6FyZ3_kgmnleZNisHHGGy-O2ZvQ_ZfrOd4bTHk4sZHbyzek-_43lLjl3d0xytuf8UPvntwvduMEIBFyooOd76xOPLbE5ln1VGQd6zSaaaIthMmOSyjfqoPZMHwpU7u0iQpbMTRMUa76OI-Ps6sC-RuLXMbQ-_ZUW?width=1500&height=1272&cropmode=none",
      "https://bn1305files.storage.live.com/y4mC6hEOVnnZ9XAprARJzKzM_dd8T37vJxN8pmAnVbyt87qiD3hvFRf-_cMLsqw8G-9X9ZCVjM5DbmAu-8b0LPflyRRWdOfacc_d8M4n2Rc-fjPJrWUmhECV1eBOCftdgjUVPQa3reCAFZYCu1vOAtz2wyh2FWSL_Pq1M7Alq_0V3hhz39WKMISyuaGFPe2TLkC?width=1232&height=1500&cropmode=none",
      "https://bn1305files.storage.live.com/y4mZwmNJQVa9zGJeEEFsSkLRAlHZH7CPgNBApIfR9y3RaqbAPn4rqZVJghkJ9qzrkfeG5F7bP2KV2jrWtCUwCWYxt9Hx_IWOsD4U7tRouwFEu2nw9DgLOQAEqnZx2GTmHve27MrtTOmYqd9wj1n_czmPUEglqkmLEV91ZybUtGIz7Yv7_G266vZVv0qi6nL-LcQ?width=1500&height=1430&cropmode=none",
    ],
    "price": 692.99,
    "stock": 11,
    "brand": "ASUS",
    "category": "Monitor",
    "description": [
      "27-inch WQHD (2560 x 1440) HDR gaming monitor with ultrafast 270Hz (overclocking) refresh rate designed for professional gamers and immersive gameplay",
      "ASUS Fast IPS technology enables a 0.5ms response time (GTG) for sharp gaming visuals with high frame rates",
      "High Dynamic Range (HDR) technology with professional color gamut delivers contrast and color performance that meets the DisplayHDR 400 certification",
      "Full HD(1920 X 1080)@120Hz & 1440P (2560 x 1440)@60Hz output on PS5, 1440P(2560 x 1440)@120Hz VRR output on Xbox Series X/S",
      "Robust connectivity with DisplayPort 1.4 DSC x2, HDMI (v2.0) x2, and USB 3.0 x2 ports",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Sceptre IPS 27-Inch Business Computer Monitor 1080p 75Hz",
    "images": [
      "https://bn1305files.storage.live.com/y4mpm2Mbi4sNToTFDaL-8M7pdrURFlYGpNvpjfK9Yy6doi_poR7K2YFEwM_t8gtXVHTqX0FSJtJsb0AIGYuMu0FXGlsKjlACU1q0kp9KiveriUn9iX3f_Kmp7a8zaqKPCvTBSFE5dNIrhIvyFGP4bRXPX9Om9OfUvIP8LD8YutSz925kZk1x-DvrOvCxMCse4KM?width=1500&height=1500&cropmode=none",
      "https://dm2305files.storage.live.com/y4m2PN0_wX2mlDQ33bzg4rmEOpgqO50XCzuK6cLJQrXjbnRf6r36rIkh_OM7R2ZGTrwBMFJxRO5ra8gzUe4iNQID8P6To763on_UlP2hPK8sM6aE0SRNWYk3kknIQlXrYw1QwMayWE9sYWOndz5AAh4VgFbssbRdAN0rIGtNg4FiPCObLXChETd428cqJeyg2Oz?width=1000&height=1000&cropmode=none",
      "https://dm2305files.storage.live.com/y4mo-AY3IH-EIsVZKAPK6lO58YKn3n0dII7AJnrwjG4d5NgvIlsEakMVZtvfnONzxIveLoTRW0nQzGT_ZkQpjuGf78cuPSmHBFzBnaXWFidbkLsrBtBiPPN9e92yurQF66C455PNUPNEeOCcjOlClkYvqiIz6CfUOAsqgZnmLU-ppIdoPSREXBC_oFccja8BUTu?width=500&height=485&cropmode=none",
    ],
    "price": 159.99,
    "stock": 12,
    "brand": "Sceptre",
    "category": "Monitor",
    "description": [
      "Wide Viewing Angles: Wide viewing angles keep all the action sharply in sight from almost any viewing position",
      "Fast Response Time: Playing fast action games and watching action adventure movies always require fast and accurate pixel response from an LED",
      "Multiple Ports: Two HDMI ports and one VGA port provide up to 75HZ refresh rate",
      "Edgeless Design: Edgeless Design completely immerses you in all the captivating action and wondrous scenery that 1080P resolution and 75Hz refresh rate",
      "Anti-Flicker: Provides a crisper picture by preventing the backlight from flickering periodically",
    ],
    "imagesDescription": [],
  },
  {
    "name": "ASUS ProArt Display 27' Monitor PA278CV - WQHD (2560 x 1440), IPS",
    "images": [
      "https://dm2305files.storage.live.com/y4mwgvwqbVE-j14Mre6fttJrAGcHKnnp00xs6R7LjRA6E4ZAcrpAyp5lSy8XEUUPBc8uNXyXAaT_8G07Uxf1xyiQEDvN2pswJ_73FUfBtvxI7cO_6pbbG196lSv_yRUr7iwpl2UyuG6MGB88AimZbO0wN7ZV4_ykM_ngclaan4ijxirnQiUhrRZyJJtP-uwwFQx?width=1500&height=1176&cropmode=none",
      "https://dm2305files.storage.live.com/y4mHgZ5Xd82zpWFoAUrxvDCX3csLdG-tdavIsGSi4UJaVbV6k9gIQF1l4ubN1-5zixU8lmWfFumDilBaAfDD_XPaUzRxYrGPuiQHxOKaPsmNLMo4s8JTFUYlB08Tq0wHy24xZX-Xd7f9eJenH_1eV0ytgSSbV0uqIUBHpaQnV-8rULmWTFOE8gZnnDv-pmc7DVC?width=1500&height=1467&cropmode=none",
      "https://dm2305files.storage.live.com/y4mIfYWAanrmkEP8GkQRjiiZS7e1RUTdkvVuov1zERQTHobiDUCpelO0Boke3zzPB8jriOLpfFliRzuNpNZwWEbSM4AnRh5h23xoi80B3g7b3-ZGE0iujZMpwzSY6RoYPQ6IVQPpGns05eCL-scDIoa_0t1q1HazLtatfuAQUukCpyOfWmGMU48uvAoY1Mo3dMf?width=1237&height=1500&cropmode=none",
    ],
    "price": 179.99,
    "stock": 23,
    "brand": "ASUS",
    "category": "Monitor",
    "description": [
      "27-inch WQHD (2560 x 1440) LED backlight display with IPS 178° wide viewing angle panel International color standard 100% sRGB",
      "Calman Verified with factory calibrated for excellent Delta E < 2 color accuracy",
      "Extensive connectivity including DP over USB-C with 65W Power Delivery, DisplayPort, HDMI, USB 3.1 hub",
      "75Hz refresh rate and Adaptive-Sync technology (48~75Hz) to animated content with fast action and eliminate screen tearing",
      "Daisy-chaining allows users to daisy chain up to four monitors for a multi-display workstation via DisplayPort",
    ],
    "imagesDescription": [],
  },

  // headset

  {
    "name": "Bose QuietComfort 45 Bluetooth Wireless Noise Cancelling Headphones",
    "images": [
      "https://dm2305files.storage.live.com/y4m6sfva6Ux-Yn88fn7IQsVgvxenWmtZPXeZBAMxJKST7ZNMCTfBpNj1qzKFUoDVpFYZOCk8-BsUuHVloDQ19yKlRFZ8L60lYtn7NEzq8XJNSZL6Cyb4z3BYl8N5npxV8PJwkc6ECT0SpnQDYj3z-X2U6eAa0WfNKaiZBhvw9RHgXiOf52uJ2bKlx-F3GCUvUNu?width=1432&height=1124&cropmode=none",
      "https://dm2305files.storage.live.com/y4mQNFf2CgBnerm8cWXUBXmJfIn64irU2kAfz2-VZA-nudeHpASpdrV54sddEXLBldZ1ssjP_DXNgrbvEFsV5NStz1bjiDoSztlPQjbNTtMYZmFeLXVgjHJpVkQD7c9SPwtnsoOQM8qiYfe1dNQg8ML2TUCybl3bArIajQLOo9SO_Gs-xDjmWWb4gxr147nb1gQ?width=1500&height=1102&cropmode=none",
      "https://dm2305files.storage.live.com/y4my-UocVRNf1paQzYyvzQmThNCvrr2m0NLiY9eb0g2muUaxRgXp-SddtYq6D-w0q3Gw1HAEXjNWNHKFEGuG0W8dZgntflut8jxHZ6V5FnNg92O8KWomDN9MirHkSnqxTDSIGI-NjUNi-2xIos4bhF9hC-ke_LjdDXAiMEMOrkp0NdyRqr3e7j5_Ft1ZUVuT4Hv?width=1500&height=1000&cropmode=none",
    ],
    "price": 329.99,
    "stock": 8,
    "brand": "Bose",
    "category": "Headphones",
    "description": [
      "Noise cancelling wireless headphones – The perfect balance of quiet, comfort, and sound. Bose uses tiny mics to measure, compare, and react to outside noise, cancelling it with opposite signals",
      "Quiet and Aware Modes – Choose Quiet Mode for full noise cancelling, or Aware Mode to bring the outside into the around ear headphones and hear your environment and your music at the same time.",
      "Around ear headphones charge via USB-C – Headphones charge via the included USB-C cable.",
      "Bluetooth wireless noise cancelling headphones – These headphones are optimized for a strong, reliable Bluetooth connection within 30 feet of the paired device.",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Jabra Evolve2 85 UC Wireless Headphones with Link380c & Charging Stand, Stereo, Black",
    "images": [
      "https://dm2305files.storage.live.com/y4mYudyM1xKW3n7lo6W9Lgr6VpFoP0UBR6jhwW-WXSOKktlA2m4VKIIDOv_ApWziFYZbvmgfJ14rrLFWFIlrAgD2SmeDFvqloDibvwF-a1ghluLkPE388SnDSF11_kvHUCN1rJgXPWYb3R6AsdZyuX37nrG1xKkVPtx0ubgnBVnu2G3GIKLPBaT4L1sMNlS4Owk?width=1448&height=1500&cropmode=none",
      "https://dm2305files.storage.live.com/y4mYet-WTEH9Dpt5krV1y66DQQfNhwwZnOk7a0XxTA907BBxT4UCmFh5EQutCKVhZ_q01iWmw1Y3Cdmv1k-Sj5P16podbhZPBXMuDCLxlgKs5m1mQdPqu-Zz2dReXcpsKipXKR-D5SJuXNuJMogVT9bUgf9Yja-zZ71Vq2N27OVTdYcc8yNB26rWGJhVrlEy4iE?width=1500&height=1499&cropmode=none",
      "https://dm2305files.storage.live.com/y4moT1z79PJYaiS3aje5QI0UZW5aeRKm2I6uIfGlc-GI7oAZ_IpL-NyQMB5R_hehCJxp1HorPjmes-C2gQ_U-XhVHM1H5toaZRBxYzP_FCY2dbK-0UXzKTlPFtiagwv4BXje82k9pmxFlZjbxDuj-x-UGLw6bIKWXYP6kzKIQS90C79KDuzt94QOCapHTeT4vpW?width=1500&height=1499&cropmode=none",
    ],
    "price": 499.99,
    "stock": 2,
    "brand": "Jabra",
    "category": "Headphones",
    "description": [
      "OUTSTANDING NOISE CANCELLATION – Jabra Evolve2 85 wireless headphones offer enhanced memory foam padding and improved ANC that cancels 54% more of the noise around you",
      "BIGGER & BETTER SOUND – This business headset has powerful leak-tolerate 40mm speakers for rich, high definition audio for calls & music",
      "INDUSTRY-LEADING BATTERY LIFE – The Jabra Evolve2 85 telework headset provides up to 37 hours of battery life on a single charge",
      "HIDDEN BOOM ARM – The foldable boom arm paired with the contemporary casual design of this Bluetooth headset means you’ll get professional sounding calls in the office and on the go",
      "UC-CERTIFIED – This Jabra headset works with all leading Unified Communications platforms, including Microsoft Teams, Cisco, Mitel, Avaya & more for truly seamless collaboration",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Skullcandy Hesh ANC Wireless Noise Cancelling Over-Ear Headphone",
    "images": [
      "https://dm2305files.storage.live.com/y4mVIEuHsxco7eBvn48_Z-E-MURsgwQPkIOWvCoZ3GaCCghnySEGP_cFV2cFN8-cYd2TgbxtMBwmbe9dBcs2lwh6_GWo3FSiAW7W8iFozc4djxGh6EZCmcebykshmkLVDo_Lok_zPbz9siQ6eEiqU42bmpV4dTaGEAXcnn8vt0kKgrfedMJoxvOd6P8Qcv4QZye?width=1383&height=1500&cropmode=none",
      "https://dm2305files.storage.live.com/y4m65SriutEtJK1dTo_bwOncg5ujRYi54rBlclkfwpaTkIQkvR26OG-6AXWW6LnZiV_U4VZ68qsxFoDGkRstbcMJMJTHsVqa1uoas7d7NtJsjX_OZY9RuAM1DvH7Fcw41zolQPM6MTy9RACCWdvNAVXQyWmre4-a2ttr3Kc2F7AaHxAh1yk_3DECoEUg_RTM9PI?width=1500&height=1500&cropmode=none",
      "https://dm2305files.storage.live.com/y4m8s_Dh1IWIcxT9wu53FE13O0WHVb2YTju-nH4xKKBNjXzkkSwGNgU5_cbT6zazvBhrl21FyIm_p7z67FIv56CX7rfNlXl2Kyv2416pGsgue3bPb6uIWPYUOJy0I6Hc7HFo2uC2Bn0q9-XGeFRcSQuXvc40hA1jEcm4VaR62t1zK0RryBtGnukUDHv4XjL-xb_?width=1500&height=1500&cropmode=none",
    ],
    "price": 133.99,
    "stock": 57,
    "brand": "Skullcandy",
    "category": "Headphones",
    "description": [
      "Active noise canceling",
      "True wireless freedom",
      "Ambient mode",
      "Rapid charge",
      "22 hours battery life",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Audio-Technica ATH-M20X Professional Studio Monitor Headphones",
    "images": [
      "https://dm2305files.storage.live.com/y4m9MpGjNipADhuwzD0e4p0Q6KVleqFhSKtXzkYGzw5ggaLom2d-lzHrUMkPqPwTkFgyAFzL3s-Ezp10hZj1ErSdAUzEjGJNP5pTqJATlrSPkRtW2VrThS9HbtvdeALXdj6gqHlYLhn2eCQNIeNXDOBmgPK9wqcgRUUfNumDxGMwt3dycyqWkBDyXTsUV8cWNgS?width=1144&height=1500&cropmode=none",
      "https://dm2305files.storage.live.com/y4mRqyPjwv8yJ-JI1cDGjuXoiSCjqEh_P3TllA_kqt5Si3S9DArMMEQVBdMQj6cr1y1fnox6SGUm1mcwp9gWBgYloBc0aUgyXtnRm2l-NQYMoaii20TJr4lUN0qMS8cKbRvONylRJZAD1vuw4NDtgiqkxsanevUXNnHkikt74oCxnjWfj-dUTqBRbOYlQQgD-Tn?width=869&height=1500&cropmode=none",
      "https://dm2305files.storage.live.com/y4mXn92wao5l7JC-w8XAnIhksZIJRaDy8OOg9OeX9iMDIkunV1CP0rR6KERftrd_XQSt61LCGTX-FTquRIj2oK39bwwAPyud-X_wDKrEj3jCa6IIbMEo6rD2-x1aUSCSFNtUA_tBXWARkuzR5OINTdOpf16NXssjouFyxy7WJMKkcUIn19oF4j5I7axfx_F8bub?width=640&height=1500&cropmode=none",
    ],
    "price": 69.99,
    "stock": 102,
    "brand": "Audio-Technica",
    "category": "Headphones",
    "description": [
      "Advanced build quality and engineering Designed for studio tracking and mixing",
      "40 millimeter drivers with rare earth magnets and copper clad aluminum wire voice coils",
      "Tune for enhanced low frequency performance",
      "Circumaural design contours around the ears for excellent sound isolation in loud environments",
      "Connectivity Technology Wired",
    ],
    "imagesDescription": [],
  },
  {
    "name": "Panasonic Full-Sized, Lightweight Long-Cord Headphones – RP-HT161-K",
    "images": [
      "https://dm2305files.storage.live.com/y4mHbmamyagiLjmtLUkSAmgdrT7a10Xk13gky_RAIMd_YIVQpBmRAApzPI0N-nb8Sg7XC7A9xzAkuMC8OcThOdcEyLIF0koXIFvIdx69wdqGSLKXyq9nyt-a65YI_bexFyX0Gq6c6Wqnpas-KuOWb2VlnJLVDqzaSpPNC1h00pdO29rO1zj7upHFMxIvB69DgzC?width=1068&height=1427&cropmode=none",
      "https://dm2305files.storage.live.com/y4mqytctgY0ITbw8bunxb3WFCKAq9vqXMEeL0ujyqxUn1cu7c9BAw6imOdUQGgc6EWQDWlWx2zGiKs4JMZl3dTzE5rGhPIMWzkikUkpd88r7sqml9dsx1kBz42xGF4qUGO9GaneIRwZ0oWuQybQVxmL2j-JivqKrHQBVVPYW6dBCBQTzNbVBoO36-qDl5hUu6C8?width=1420&height=1244&cropmode=none",
      "https://dm2305files.storage.live.com/y4mgdJXwvAFKweVFSxhbcAW4A5J5qRVcW2SpUWUVOvGGA2dFKDy2LbI4uRqSdS4jNc5G_RyqU9vnfSbg8FBEJbGPVgGLQySTu1utFh83Dj0L4RzX9ZAIR5PhgJxqVdBDcIWwH3GgJsjL0x59fzpjv6S_kJNFf8B--s7MH-hmhZ57cbKRwontTYxl5ATAl9vovPh?width=1441&height=1301&cropmode=none",
    ],
    "price": 16.99,
    "stock": 77,
    "brand": "    Panasonic",
    "category": "Headphones",
    "description": [
      "Wired over the Ear Headphones: Full size, classic style Headphones deliver balanced, high frequency sound on par with higher priced headphones for maximum value and hours of listening enjoyment",
      "Powerful Bass, Vocals and Lyrics: Dual 30 millimeter neodymium driver units easily handle up to 1000Mw maximum power input for satisfying bass plus mid-range and high frequency trebles for clear vocals and lyrics",
      "Padded for Comfort: Plush padded earpads softly surround the entire ear to minimize ambient noise and Distractions, and a smooth, quick adjust headband easily conforms to the head for optimum fit and comfort",
      "Extended Headphone Cord: An extra-long, 6.5 feet audio cord gives you plenty of space to sit back and relax while watching movies and TV, and the freedom to move about while gaming",
      "Sound with style: Sleek, distinctive matte black finish and durable, lightweight design add a clear look of style and comfort wherever you go",
    ],
    "imagesDescription": [],
  },
];
